import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { createHash } from 'node:crypto';
import { CONTRACT_VERSION, openApiDocument, validateBinding, type RequestBinding, type C1ModelRelease, type BreakGlassGrant, type ExecutionCommand, type ExecutionStatus, type EventEnvelope } from '../../../packages/contracts/src/index.js';
import { DeterministicEvidenceAdmission } from '../../../packages/platform-core/src/evidence-admission.js';
import { DeterministicKernel } from '../../../packages/platform-core/src/kernel.js';
import { LogisticsProposalGenerator } from '../../../packages/platform-core/src/proposal-generator.js';
import { ReplayableStateProjector } from '../../../packages/platform-core/src/state-projector.js';
import { HumanReviewGate } from '../../../packages/platform-core/src/human-review.js';
import { ShadowEvaluator } from '../../../packages/platform-core/src/shadow-evaluator.js';
import { SimulatedIdentityVerifier, type IdentityVerifier } from '../../../packages/platform-core/src/auth.js';
import { InMemoryPlatformRepositories, type InstitutionSourceRecord } from '../../../packages/platform-core/src/repositories.js';
import { HashLinkedReceiptService } from '../../../packages/platform-core/src/receipt-service.js';
import { canonicalize, DeterministicKmsProvider, KmsReceiptCustody, type ReceiptSigner } from '../../../packages/platform-core/src/receipt-custody.js';
import { ShadowExecutionAssurance } from '../../../packages/platform-core/src/execution-assurance.js';
import { ForensicReconstructionService } from '../../../packages/platform-core/src/reconstruction.js';
import { assertRuntimeProfile, type RuntimeDependencies, type RuntimeProfile } from './runtime.js';
import { GovernedInstitutionTransitionService } from '../../../packages/platform-core/src/institution-transition-service.js';
import type { TransitionFaultInjector } from '../../../packages/platform-core/src/institution-transition-service.js';

const repositories = new InMemoryPlatformRepositories();
const stableHash = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const relevantState = (values: Record<string, unknown>) => ({ memphis_capacity: values.memphis_capacity, commitments_at_risk: values.commitments_at_risk });
const executionEvent = (command: ExecutionCommand & { tenant_id: string }, eventType: EventEnvelope['event_type'], actorId: string, bind: RequestBinding, payload: Record<string, unknown>): EventEnvelope => ({ event_id: `execution-${command.command_id}-${eventType}-${bind.idempotency_key}`, tenant_id: command.tenant_id, event_type: eventType, actor_id: actorId, actor_type: 'HUMAN', scope_id: command.resource, incident_id: command.incident_id, occurred_at: bind.request_timestamp, observed_at: bind.request_timestamp, available_to_controller_at: bind.request_timestamp, recorded_at: bind.request_timestamp, correlation_id: bind.correlation_id, trace_id: bind.trace_id, state_version_before: command.state_version, state_version_after: command.state_version, policy_version: 'EXECUTION-ASSURANCE-v1', payload, payload_hash: stableHash(payload), previous_record_hash: 'sha256:execution', signature: 'simulated', simulated: true });
const state = async (repositories: RuntimeDependencies['repositories'], tenantId: string, scopeId: string) => new ReplayableStateProjector().project(await repositories.getEvents(tenantId, undefined).then(events => events.filter(event => event.scope_id === scopeId)));
const modelReleases: C1ModelRelease[] = [{ release_id: 'c1-shadow-0.9.1', model_hash: 'sha256:c1-shadow-demo', adapter_hash: 'sha256:no-adapter', actionnet_version: 'actionnet-v0.4', status: 'QUALIFIED_SHADOW', capabilities: [{ capability_id: 'c1.institutional-assessment', name: 'Institutional situation assessment', description: 'Diagnoses operational changes and identifies affected commitments.', release_id: 'c1-shadow-0.9.1', model_hash: 'sha256:c1-shadow-demo', adapter_hash: 'sha256:no-adapter', actionnet_version: 'actionnet-v0.4', qualification_status: 'QUALIFIED_SHADOW', qualified_workflows: ['logistics.recovery'], permitted_operating_modes: ['SHADOW'], input_schema: 'InstitutionalSituation.v1', output_schema: 'Assessment.v1', required_context: ['state', 'evidence', 'commitments', 'authority'], evaluation_ids: ['eval-transfer-seed-1', 'eval-transfer-seed-2'], evaluation_results: { mean: 0.8594, seed_1: 0.8875, seed_2: 0.8313 }, safety_constraints: ['No authority grant', 'No execution credentials', 'Citations required'], unsupported_conditions: ['Unadmitted evidence', 'Missing state version'], latency_limit_ms: 10000, cost_limit: 'shadow-only', fallback_behavior: 'ABSTAIN and request human review', approval_authority: 'Institutional Kernel', qualified_at: '2026-09-24T00:00:00Z', expires_at: '2026-12-23T00:00:00Z' }] }];
const json = (request: IncomingMessage) => new Promise<Record<string, unknown>>((resolve, reject) => { let body = ''; request.on('data', chunk => { body += chunk; }); request.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('invalid json')); } }); });
const reply = (response: ServerResponse, status: number, body: unknown) => { response.statusCode = status; response.setHeader('content-type', 'application/json'); response.end(JSON.stringify(body)); };
const failure = (response: ServerResponse, code: string, message: string, correlation_id = 'unknown') => reply(response, code === 'INTERNAL_ERROR' ? 500 : code === 'VALIDATION_FAILED' ? 400 : code === 'PERMISSION_DENIED' ? 403 : code === 'STATE_STALE' ? 409 : 422, { error: { code, message, correlation_id } });
const failureResult = (code: string, message: string, correlation_id = 'unknown') => ({ status: code === 'VALIDATION_FAILED' ? 400 : code === 'PERMISSION_DENIED' ? 403 : code === 'STATE_STALE' ? 409 : 422, body: { error: { code, message, correlation_id } } });
const transactionResponse = async <T extends { status: number; body: unknown }>(repositories: RuntimeDependencies['repositories'], tenantId: string, response: ServerResponse, work: (scoped: RuntimeDependencies['repositories']) => Promise<T>) => { const result = await repositories.transaction(tenantId, work); return reply(response, result.status, result.body); };
class StateConflictError extends Error { constructor(public readonly correlationId: string) { super('State changed while projecting the event'); } }
const binding = (body: Record<string, unknown>) => body.binding as RequestBinding | undefined;
const validateRequest = (body: Record<string, unknown>) => validateBinding(binding(body));
const capabilityFor = (method: string, path: string): string | null => {
  if (method === 'POST' && path === '/v1/events') return 'event:submit';
  if (method === 'POST' && path === '/v1/proposals') return 'proposal:create';
  if (method === 'POST' && path === '/v1/reviews') return 'review:approve';
  if (method === 'POST' && path === '/v1/shadow-evaluations') return 'shadow:evaluate';
  if (method === 'POST' && path === '/v1/outcomes') return 'outcome:record';
  if (method === 'POST' && path === '/v1/executions') return 'proposal:create';
  if (method === 'POST' && /^\/v1\/executions\/[^/]+\/dispatch$/.test(path)) return 'outcome:record';
  if (method === 'POST' && /^\/v1\/executions\/[^/]+\/(acknowledge|outcome|verify|reconcile|cancel|compensate|takeover)$/.test(path)) return 'outcome:record';
  if (method === 'POST' && /^\/v1\/outbox\/[^/]+\/requeue$/.test(path)) return 'outbox:requeue';
  if (method === 'POST' && path === '/v1/break-glass/requests') return 'break-glass:request';
  if (method === 'POST' && /\/v1\/break-glass\/[^/]+\/(approve|activate|revoke)$/.test(path)) return path.endsWith('/revoke') ? 'break-glass:revoke' : 'break-glass:approve';
  if (method === 'POST' && /\/v1\/break-glass\/[^/]+\/use$/.test(path)) return 'break-glass:use';
  if (method === 'GET' && path.startsWith('/v1/break-glass/')) return 'break-glass:read';
  if (method === 'GET' && path.startsWith('/v1/reconstructions/')) return 'reconstruction:read';
  if (method === 'POST' && path.startsWith('/v1/reconstructions/') && path.endsWith('/export')) return 'reconstruction:read';
  if (method === 'GET' && path.startsWith('/v1/receipts/')) return 'receipt:read';
  if (method === 'GET' && path.startsWith('/v1/model-releases')) return 'model-release:administer';
  if (method === 'POST' && /^\/v1\/institutions\/[^/]+\/sources$/.test(path)) return 'institution:compile';
  if (method === 'GET' && /^\/v1\/institutions\/[^/]+\/sources(?:\/[^/]+\/versions)?$/.test(path)) return 'institution:read';
  if (method === 'GET' && path === '/v1/institution-compilations') return 'institution:read';
  if (method === 'GET' && /^\/v1\/institution-compilations\/[^/]+$/.test(path)) return 'institution:read';
  if (method === 'POST' && /^\/v1\/institution-releases\/[^/]+\/transition$/.test(path)) return 'institution:compile';
  if (method === 'GET' && /^\/v1\/institution-releases\/[^/]+$/.test(path)) return 'institution:read';
  if (method === 'GET' && (path.startsWith('/v1/state/') || path.startsWith('/v1/incidents/') || path.startsWith('/v1/proposals/') || path.startsWith('/v1/decisions/') || path.startsWith('/v1/outcomes/') || path.startsWith('/v1/executions/'))) return 'evidence:read';
  return null;
};
const rolesForCapability: Record<string, string[]> = { 'event:submit': ['operator', 'connector'], 'evidence:read': ['operator', 'auditor', 'investigator', 'administrator'], 'evidence:restricted:read': ['auditor', 'investigator'], 'proposal:create': ['operator', 'administrator'], 'review:approve': ['operator', 'reviewer', 'administrator'], 'shadow:evaluate': ['operator', 'administrator'], 'outcome:record': ['operator', 'connector', 'administrator'], 'receipt:read': ['operator', 'auditor', 'investigator', 'administrator'], 'reconstruction:read': ['auditor', 'investigator', 'administrator'], 'outbox:requeue': ['auditor', 'investigator', 'administrator'], 'model-release:administer': ['administrator'], 'institution:compile': ['administrator'], 'institution:read': ['administrator', 'auditor', 'investigator'], 'break-glass:request': ['operator', 'administrator'], 'break-glass:approve': ['administrator'], 'break-glass:revoke': ['administrator', 'auditor'], 'break-glass:read': ['operator', 'auditor', 'investigator', 'administrator'], 'break-glass:use': ['operator', 'auditor', 'investigator', 'administrator'] };

export type ControlPlaneServerOptions = Partial<RuntimeDependencies> & { profile?: RuntimeProfile; identityVerifier?: IdentityVerifier; receiptSigner?: ReceiptSigner; corsOrigin?: string; faultInjector?: TransitionFaultInjector };
export function createControlPlaneServer(options: ControlPlaneServerOptions = {}) {
  const profile = options.profile ?? 'LOCAL';
  const identityVerifier = options.identityVerifier ?? new SimulatedIdentityVerifier({ tenant_id: 'meridian-demo', actor_id: 'operator-01', actor_type: 'HUMAN', roles: ['operator'], expires_at: '2099-01-01T00:00:00Z' });
  const runtimeDependencies: RuntimeDependencies = { repositories: options.repositories ?? repositories, identityVerifier, receiptSigner: options.receiptSigner ?? new KmsReceiptCustody(new DeterministicKmsProvider(), 'kms-test-key'), tenantIsolation: options.tenantIsolation ?? profile === 'LOCAL', auditLogging: options.auditLogging ?? profile === 'LOCAL', signingKeyMode: options.signingKeyMode ?? 'DEVELOPMENT' };
  assertRuntimeProfile(profile, runtimeDependencies);
  const institutionTransitionService = new GovernedInstitutionTransitionService(runtimeDependencies.repositories, options.faultInjector);
  return createServer(async (request, response) => {
    try {
    const origin = request.headers.origin;
    if (origin && origin === options.corsOrigin) response.setHeader('access-control-allow-origin', origin);
    response.setHeader('vary', 'Origin');
    if (request.method === 'OPTIONS') { response.setHeader('access-control-allow-headers', 'authorization,content-type,x-correlation-id,x-trace-id'); response.setHeader('access-control-allow-methods', 'GET,POST,OPTIONS'); return reply(response, 204, null); }
    const url = new URL(request.url ?? '/', 'http://localhost');
    if (request.method === 'GET' && url.pathname === '/openapi.json') return reply(response, 200, openApiDocument());
    let body: Record<string, unknown> = {};
    try { if (request.method === 'POST') body = await json(request); } catch { return failure(response, 'VALIDATION_FAILED', 'Request body must be valid JSON'); }
    const bind = binding(body);
    if (request.method === 'GET' && url.pathname === '/healthz') return reply(response, 200, { status: 'ok', profile });
    if (request.method === 'GET' && url.pathname === '/readyz') return reply(response, profile === 'LOCAL' || (runtimeDependencies.tenantIsolation && runtimeDependencies.auditLogging) ? 200 : 503, { status: profile === 'LOCAL' ? 'ready-simulated' : 'ready' });
    const principal = await runtimeDependencies.identityVerifier.verify(request);
    const authenticatedRoute = url.pathname.startsWith('/v1/');
    if (authenticatedRoute && !principal) return reply(response, 401, { error: { code: 'AUTHENTICATION_REQUIRED', message: 'Authentication is required', correlation_id: request.headers['x-correlation-id'] ?? 'unknown' } });
    if (authenticatedRoute && principal?.active === false) return failure(response, 'PERMISSION_DENIED', 'Actor is inactive');
    if (request.method === 'POST' && principal && bind && (bind.tenant_id !== principal.tenant_id || bind.actor_id !== principal.actor_id)) return failure(response, 'PERMISSION_DENIED', 'Request identity does not match verified identity', principal.actor_id);
    if (request.method === 'POST' && (!validateRequest(body) || bind?.contract_version !== CONTRACT_VERSION)) return failure(response, 'VALIDATION_FAILED', 'Required request binding is missing or invalid', bind?.correlation_id);
    const requiredCapability = capabilityFor(request.method ?? 'GET', url.pathname);
    if (requiredCapability) {
      const allowedRoles = rolesForCapability[requiredCapability] ?? [];
      const matchingRole = principal?.roles.find(role => allowedRoles.includes(role));
      if (!matchingRole) return failure(response, 'PERMISSION_DENIED', 'The verified principal lacks the required capability', request.headers['x-correlation-id'] as string ?? 'unknown');
      const membership = await runtimeDependencies.repositories.transaction(principal!.tenant_id, repositories => repositories.getActorMembership(principal!.tenant_id, principal!.actor_id, matchingRole));
      if (!membership?.active || (membership.mandate_expires_at && new Date(membership.mandate_expires_at).getTime() <= Date.now())) return failure(response, 'PERMISSION_DENIED', 'The actor mandate is inactive or expired');
      const requestedScope = String(body.scope_id ?? request.headers['x-facility-scope'] ?? '');
      if (membership.facility_scope && membership.facility_scope !== '*' && requestedScope && membership.facility_scope !== requestedScope) return failure(response, 'PERMISSION_DENIED', 'The actor is outside the authorized facility scope');
    }
    const currentState = bind ? await runtimeDependencies.repositories.transaction(principal!.tenant_id, repositories => state(repositories, principal!.tenant_id, String(body.scope_id ?? 'memphis-fulfillment'))) : { version: 141, values: {} };
    if (request.method === 'POST' && url.pathname !== '/v1/events' && url.pathname !== '/v1/reviews' && bind?.expected_state_version !== undefined && bind.expected_state_version !== currentState.version) return failure(response, 'STATE_STALE', 'Expected state version is stale', bind.correlation_id);
    if (request.method === 'POST' && url.pathname === '/v1/events') {
      return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
        await repositories.lockScope(`${principal!.tenant_id}:${String(body.scope_id ?? 'memphis-fulfillment')}`);
        const transactionState = await state(repositories, principal!.tenant_id, String(body.scope_id ?? 'memphis-fulfillment'));
        const payload = (body.payload ?? {}) as Record<string, unknown>;
        const event = { event_id: String(body.event_id ?? `evt-${Date.now()}`), tenant_id: principal!.tenant_id, event_type: 'OBSERVATION_RECEIVED' as const, actor_id: bind!.actor_id, actor_type: 'CONNECTOR' as const, scope_id: String(body.scope_id ?? 'memphis-fulfillment'), incident_id: String(body.incident_id ?? 'INC-1042'), occurred_at: typeof body.occurred_at === 'string' ? body.occurred_at : bind!.request_timestamp, observed_at: typeof body.observed_at === 'string' ? body.observed_at : bind!.request_timestamp, available_to_controller_at: typeof body.available_to_controller_at === 'string' ? body.available_to_controller_at : bind!.request_timestamp, recorded_at: bind!.request_timestamp, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: transactionState.version, state_version_after: transactionState.version, policy_version: String(body.policy_version ?? 'POL-LOG-07 v18'), payload, payload_hash: stableHash(payload), previous_record_hash: 'sha256:api', signature: 'simulated', simulated: true as const };
        const operationKey = `POST:/v1/events:${bind!.idempotency_key}`;
        const existing = await repositories.getIdempotency(principal!.tenant_id, operationKey);
        if (existing !== undefined) return { status: 200, body: { data: existing, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
        if (bind!.expected_state_version !== undefined && bind!.expected_state_version !== transactionState.version) { console.error('Event state version conflict', { expected: bind!.expected_state_version, actual: transactionState.version, operationKey }); return failureResult('STATE_STALE', 'Expected state version is stale', bind!.correlation_id); }
        const idempotency = await repositories.claimIdempotency(principal!.tenant_id, operationKey, event);
        if (!idempotency.claimed) return { status: 200, body: { data: idempotency.response, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
        const appended = await repositories.appendEvent(event);
        if (!appended) return { status: 200, body: { data: event, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
        const evidence = new DeterministicEvidenceAdmission().admit({ ...payload, evidence_id: payload.evidence_id ?? `${event.event_id}:evidence` });
        for (const record of evidence) {
          await repositories.putEvidence({ ...record, tenant_id: principal!.tenant_id });
          await repositories.appendEvent({ ...event, event_id: `${event.event_id}:evidence:${record.evidence_id}`, event_type: 'EVIDENCE_ADMITTED', actor_id: 'evidence-admission', actor_type: 'SYSTEM', causation_id: event.event_id, payload: { ...record }, payload_hash: stableHash(record) });
          await repositories.linkEvidence({ tenant_id: principal!.tenant_id, relationship_id: `${event.event_id}:${record.evidence_id}`, event_id: event.event_id, evidence_id: record.evidence_id, relationship_type: record.status === 'restricted' ? 'RESTRICTED_FROM' : record.status === 'disputed' ? 'DISPUTED_BY' : record.status === 'missing' ? 'REJECTED_FOR' : 'ADMITTED_FOR' });
        }
        const admissible = evidence.filter(record => ['observed', 'verified', 'reported', 'inferred'].includes(record.status));
        if (!admissible.length) return { status: 202, body: { data: { ...event, admission: 'RESTRICTED_OR_REJECTED' }, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
        const projectedEvent = { ...event, event_id: `${event.event_id}:state`, event_type: 'STATE_PROJECTED' as const, actor_id: 'control-plane', actor_type: 'SYSTEM' as const, state_version_before: transactionState.version, state_version_after: transactionState.version + 1, causation_id: event.event_id, payload: { capacity_units: Number(payload.capacity_units), commitments_at_risk: Number(payload.commitments_at_risk ?? 0) } };
        await repositories.appendEvent(projectedEvent);
        const projected = await state(repositories, bind!.tenant_id, event.scope_id);
        const projectedVersion = transactionState.version + 1;
        const nextValues = projected.values;
        const stateHash = stableHash(nextValues);
        const previousValues = transactionState.values as Record<string, unknown>;
        const nextValueMap = nextValues as Record<string, unknown>;
        const diff = Object.fromEntries([...new Set([...Object.keys(previousValues), ...Object.keys(nextValueMap)])].filter(key => JSON.stringify(previousValues[key]) !== JSON.stringify(nextValueMap[key])).map(key => [key, { previous: previousValues[key], next: nextValueMap[key] }]));
        const persisted = await repositories.putState({ tenant_id: bind!.tenant_id, incident_id: event.incident_id, scope_id: event.scope_id, state_version: projectedVersion, status: 'OPEN', values: nextValues, state_hash: stateHash }, transactionState.version);
        if (!persisted) throw new StateConflictError(bind!.correlation_id);
        await repositories.putStateDiff({ tenant_id: bind!.tenant_id, scope_id: event.scope_id, version: projectedVersion, diff, state_hash: stateHash });
        await repositories.enqueueOutbox({ outbox_id: `outbox-${event.event_id}`, tenant_id: principal!.tenant_id, dedupe_key: `event:${event.event_id}:projected`, topic: 'STATE_PROJECTED', aggregate_id: event.incident_id, payload: { event_id: event.event_id, scope_id: event.scope_id, state_version: projectedVersion }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: projectedVersion });
        return { status: 201, body: { data: { ...event, state_version_after: projectedVersion }, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
      });
    }
    if (request.method === 'POST' && url.pathname === '/v1/proposals') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const scopeId = String(body.scope_id ?? 'memphis-fulfillment');
      const transactionState = await state(repositories, principal!.tenant_id, scopeId);
      if (bind!.expected_state_version !== undefined && bind!.expected_state_version !== transactionState.version) return failureResult('STATE_STALE', 'Expected state version is stale', bind!.correlation_id);
      if ((body.policy_version && body.policy_version !== 'POL-LOG-07 v18') || (body.authority_version && body.authority_version !== 'AUTH-v1') || (body.mandate_version && body.mandate_version !== 'MND-v1') || (body.commitment_version && body.commitment_version !== 'CMT-v1') || (body.domain_pack_version && body.domain_pack_version !== 'logistics-v1')) return failureResult('VALIDATION_FAILED', 'Proposal dependency version is not active', bind!.correlation_id);
      const releaseId = String(body.release_id ?? 'c1-shadow-0.9.1');
      const release = modelReleases.find(item => item.release_id === releaseId);
      const capabilityId = String(body.capability_id ?? 'c1.institutional-assessment');
      const capability = release?.capabilities.find(item => item.capability_id === capabilityId);
      if (!release || !['QUALIFIED_SHADOW', 'QUALIFIED_ASSISTED', 'QUALIFIED_PRODUCTION'].includes(release.status) || !capability || !['QUALIFIED_SHADOW', 'QUALIFIED_ASSISTED', 'QUALIFIED_PRODUCTION'].includes(capability.qualification_status) || !capability.permitted_operating_modes.includes('SHADOW') || Date.parse(capability.expires_at) <= Date.now() || !capability.qualified_workflows.includes('logistics.recovery')) return failureResult('VALIDATION_FAILED', 'C1 release is unqualified, expired or outside the requested workflow/mode', bind!.correlation_id);
      const evidence = new DeterministicEvidenceAdmission().admit({ capacity_units: Number(transactionState.values.memphis_capacity ?? 0), evidence_id: `state-${transactionState.version}`, source: 'committed-state', version: `v${transactionState.version}`, citation_text: 'Evidence bound to the committed state version.' });
      if (!evidence.length) return failureResult('EVIDENCE_MISSING', 'No admitted evidence is available for this state version', bind!.correlation_id);
      const generated = new LogisticsProposalGenerator().create(transactionState, evidence);
      const modelAssumptions = body.model_timeout === true ? ['MODEL_TIMEOUT'] : body.model_output_valid === false ? ['MODEL_OUTPUT_INVALID'] : [];
      const proposal = { ...generated, assumptions: [...generated.assumptions, ...modelAssumptions], proposal_id: String(body.proposal_id ?? generated.proposal_id), context: { tenant_id: principal!.tenant_id, incident_id: generated.incident_id, state_version: transactionState.version, state_hash: stableHash(relevantState(transactionState.values)), evidence_versions: Object.fromEntries(evidence.map(item => [item.evidence_id, item.version])), policy_version: generated.policy_version, authority_version: String(body.authority_version ?? 'AUTH-v1'), mandate_version: String(body.mandate_version ?? 'MND-v1'), commitment_version: String(body.commitment_version ?? 'CMT-v1'), c1_release: release.release_id, adapter_version: release.adapter_hash, actionnet_version: release.actionnet_version, domain_pack_version: String(body.domain_pack_version ?? 'logistics-v1'), capability_id: capability.capability_id, operating_mode: 'SHADOW' as const }, status: 'PENDING_KERNEL' as const };
      const existing = await repositories.getProposal(principal!.tenant_id, proposal.proposal_id);
      if (existing) return { status: 200, body: { data: existing, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
      const preliminaryDecision = new DeterministicKernel().evaluateAt(proposal, transactionState.version, 30000);
      const finalStatus = preliminaryDecision.disposition === 'APPROVAL_REQUIRED' ? 'REVIEW_REQUIRED' as const : proposal.status;
      const proposalHash = stableHash({ ...proposal, status: finalStatus });
      const boundProposal = { ...proposal, status: finalStatus, proposal_hash: proposalHash };
      const initialDecision = new DeterministicKernel().evaluateAt(boundProposal, transactionState.version, 30000);
      const storedProposal = { ...boundProposal, tenant_id: principal!.tenant_id };
      await repositories.putIncident({ tenant_id: principal!.tenant_id, incident_id: boundProposal.incident_id, scope_id: scopeId, state_version: transactionState.version, status: 'OPEN' });
      await repositories.putProposal(storedProposal);
      await repositories.putKernelDecision({ ...initialDecision, tenant_id: principal!.tenant_id, recorded_at: bind!.request_timestamp });
      await repositories.appendEvent({ event_id: `proposal:${boundProposal.proposal_id}`, tenant_id: principal!.tenant_id, event_type: 'PROPOSAL_CREATED', actor_id: principal!.actor_id, actor_type: principal!.actor_type, scope_id: scopeId, incident_id: boundProposal.incident_id, occurred_at: bind!.request_timestamp, observed_at: bind!.request_timestamp, available_to_controller_at: bind!.request_timestamp, recorded_at: bind!.request_timestamp, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: transactionState.version, state_version_after: transactionState.version, policy_version: boundProposal.policy_version, model_release: release.release_id, payload: { proposal: storedProposal }, payload_hash: proposalHash, previous_record_hash: 'sha256:proposal', signature: 'simulated', simulated: true });
      await repositories.appendEvent({ event_id: `decision:${initialDecision.decision_id}`, tenant_id: principal!.tenant_id, event_type: 'KERNEL_DECIDED', actor_id: 'institutional-kernel', actor_type: 'KERNEL', scope_id: scopeId, incident_id: boundProposal.incident_id, occurred_at: bind!.request_timestamp, observed_at: bind!.request_timestamp, available_to_controller_at: bind!.request_timestamp, recorded_at: bind!.request_timestamp, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: transactionState.version, state_version_after: transactionState.version, policy_version: boundProposal.policy_version, model_release: release.release_id, payload: initialDecision, payload_hash: stableHash(initialDecision), previous_record_hash: proposalHash, signature: 'simulated', simulated: true });
      await repositories.enqueueOutbox({ outbox_id: `outbox-${boundProposal.proposal_id}`, tenant_id: principal!.tenant_id, dedupe_key: `proposal:${boundProposal.proposal_id}`, topic: 'PROPOSAL_CREATED', aggregate_id: boundProposal.incident_id, payload: { proposal_id: boundProposal.proposal_id, state_version: transactionState.version }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: transactionState.version });
      return { status: 201, body: { data: storedProposal, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
    });
    if (request.method === 'POST' && url.pathname === '/v1/reviews') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id));
      if (!proposal) return failureResult('VALIDATION_FAILED', 'Proposal not found', bind?.correlation_id);
      const prior = await repositories.getIdempotency(principal!.tenant_id, `POST:/v1/reviews:${bind!.idempotency_key}`);
      if (prior !== undefined) return { status: 200, body: { data: prior, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
      const existingReview = await repositories.getReview(principal!.tenant_id, proposal.proposal_id);
      if (existingReview) { const existingDecision = await repositories.getKernelDecision(principal!.tenant_id, proposal.proposal_id); if (existingDecision) return { status: 200, body: { data: existingDecision, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } }; }
      if (!body.proposal_hash || body.proposal_hash !== proposal.proposal_hash || (proposal.context?.state_hash && body.context_hash !== proposal.context.state_hash)) return failureResult('VALIDATION_FAILED', 'Review must bind to the exact proposal and decision context hashes', bind!.correlation_id);
      const scopeId = String(body.scope_id ?? proposal.context?.incident_id ?? 'memphis-fulfillment');
      const transactionState = await state(repositories, principal!.tenant_id, scopeId);
      const currentStateHash = stableHash(relevantState(transactionState.values));
      const relevantChanged = proposal.context?.state_hash !== currentStateHash;
      if (proposal.context && relevantChanged) return failureResult('STATE_STALE', 'Proposal decision context is stale', bind!.correlation_id);
      if (proposal.context && (proposal.context.policy_version !== 'POL-LOG-07 v18' || proposal.context.authority_version !== 'AUTH-v1' || proposal.context.commitment_version !== 'CMT-v1' || proposal.context.domain_pack_version !== 'logistics-v1')) return failureResult('STATE_STALE', 'Proposal policy or authority context is no longer active', bind!.correlation_id);
      const membership = await repositories.getActorMembership(principal!.tenant_id, principal!.actor_id, principal!.roles.includes('administrator') ? 'administrator' : 'operator');
      const mandateLimit = membership?.financial_limit ?? 30000;
      if (!membership?.active || (membership.mandate_expires_at && Date.parse(membership.mandate_expires_at) <= Date.now())) return failureResult('MANDATE_INVALID', 'Reviewer mandate is expired or revoked', bind!.correlation_id);
      const reviewId = `review-${proposal.proposal_id}`;
      const decisionProposal = proposal.context && proposal.context.state_version !== transactionState.version ? { ...proposal, state_version: transactionState.version } : proposal;
      const decision = new HumanReviewGate().reevaluate(decisionProposal, body.approved === true, transactionState.version, mandateLimit);
      await repositories.putKernelDecision({ ...decision, tenant_id: principal!.tenant_id, recorded_at: bind!.request_timestamp });
      await repositories.putReview({ tenant_id: principal!.tenant_id, review_id: reviewId, proposal_id: proposal.proposal_id, actor_id: bind!.actor_id, approved: body.approved === true, recorded_at: bind!.request_timestamp, proposal_hash: proposal.proposal_hash, context_hash: proposal.context?.state_hash });
      await repositories.claimIdempotency(principal!.tenant_id, `POST:/v1/reviews:${bind!.idempotency_key}`, decision);
      await repositories.appendEvent({ event_id: `authorization-${decision.decision_id}`, tenant_id: principal!.tenant_id, event_type: 'HUMAN_REVIEWED', actor_id: principal!.actor_id, actor_type: principal!.actor_type, scope_id: scopeId, incident_id: proposal.incident_id, occurred_at: bind!.request_timestamp, observed_at: bind!.request_timestamp, available_to_controller_at: bind!.request_timestamp, recorded_at: bind!.request_timestamp, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: transactionState.version, state_version_after: transactionState.version, policy_version: proposal.policy_version, payload: { principal: principal!.actor_id, capability: 'review:approve', resource: proposal.proposal_id, proposal_hash: proposal.proposal_hash, approved: body.approved === true, disposition: decision.disposition }, payload_hash: stableHash(decision), previous_record_hash: 'sha256:authorization', signature: 'simulated', simulated: true });
      await repositories.enqueueOutbox({ outbox_id: `outbox-review-${proposal.proposal_id}`, tenant_id: principal!.tenant_id, dedupe_key: `review:${proposal.proposal_id}:${proposal.proposal_hash}`, topic: 'KERNEL_REEVALUATION', aggregate_id: proposal.incident_id, payload: { proposal_id: proposal.proposal_id, decision_id: decision.decision_id, state_version: transactionState.version, proposal_hash: proposal.proposal_hash }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: transactionState.version });
      return { status: 200, body: { data: decision, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
    });
    if (request.method === 'POST' && url.pathname === '/v1/shadow-evaluations') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => { const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id)); if (!proposal) return failureResult('VALIDATION_FAILED', 'Proposal not found', bind?.correlation_id); const shadow = new ShadowEvaluator().record(proposal); await repositories.putShadow({ proposal_id: shadow.proposal_id, recorded_at: shadow.recommendation_recorded_at, executed: false, credentials: 'NONE', tenant_id: principal!.tenant_id }); await repositories.enqueueOutbox({ outbox_id: `outbox-shadow-${shadow.proposal_id}`, tenant_id: principal!.tenant_id, dedupe_key: `shadow:${shadow.proposal_id}`, topic: 'SHADOW_EVALUATION_RECORDED', aggregate_id: proposal.incident_id, payload: { proposal_id: shadow.proposal_id, executed: false }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: proposal.state_version }); return { status: 201, body: { data: shadow, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } }; });
    if (request.method === 'POST' && url.pathname === '/v1/executions') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id));
      const decision = proposal ? await repositories.getKernelDecision(principal!.tenant_id, proposal.proposal_id) : null;
      if (!proposal || !decision) return failureResult('VALIDATION_FAILED', 'Proposal or Kernel decision not found', bind?.correlation_id);
      if (decision.disposition !== 'ALLOW') return failureResult('PERMISSION_DENIED', `Execution requires Kernel ALLOW; received ${decision.disposition}`, bind?.correlation_id);
      const now = bind!.request_timestamp; const expiresAt = String(body.expires_at ?? new Date(Date.now() + 300000).toISOString());
      const command = await new ShadowExecutionAssurance(repositories).create({ tenant_id: principal!.tenant_id, command_id: String(body.command_id ?? `cmd-${bind!.idempotency_key}`), incident_id: proposal.incident_id, proposal_id: proposal.proposal_id, authorization_id: decision.decision_id, proposal_hash: proposal.proposal_hash ?? stableHash(proposal), state_version: proposal.state_version, external_idempotency_key: String(body.external_idempotency_key ?? `external-${bind!.idempotency_key}`), connector: String(body.connector ?? 'none'), resource: String(body.resource ?? proposal.incident_id), credential_scope: 'NONE', dispatch_requested_at: now, expires_at: expiresAt });
      await repositories.appendEvent(executionEvent(command, 'DISPATCH_REQUESTED', principal!.actor_id, bind!, { command_id: command.command_id, command_hash: command.command_hash, authorization_id: command.authorization_id, mode: 'SHADOW' }));
      return { status: 201, body: { data: command, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
    });
    if (request.method === 'POST' && /^\/v1\/executions\/[^/]+\/dispatch$/.test(url.pathname)) return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const command = await repositories.getExecution(principal!.tenant_id, url.pathname.split('/')[3]); if (!command) return failureResult('VALIDATION_FAILED', 'Execution command not found', bind?.correlation_id);
      const result = await new ShadowExecutionAssurance(repositories).dispatch(command);
      await repositories.appendEvent(executionEvent(result, result.status === 'DISPATCH_REJECTED' ? 'DISPATCH_REJECTED' : 'DISPATCH_FAILED', principal!.actor_id, bind!, { status: result.status, rejection: 'SHADOW_DISPATCH_DISABLED' }));
      return { status: 422, body: { error: { code: 'SHADOW_DISPATCH_DISABLED', message: 'Shadow mode has no connector credentials or dispatch path', correlation_id: bind?.correlation_id }, data: result } };
    });
    if (request.method === 'POST' && /^\/v1\/executions\/[^/]+\/(acknowledge|outcome|verify|reconcile|cancel|compensate|takeover)$/.test(url.pathname)) return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const command = await repositories.getExecution(principal!.tenant_id, url.pathname.split('/')[3]); if (!command) return failureResult('VALIDATION_FAILED', 'Execution command not found', bind?.correlation_id);
      const action = url.pathname.split('/').at(-1)!; const next: Record<string, ExecutionStatus> = { acknowledge: 'ACKNOWLEDGED', outcome: 'OUTCOME_REPORTED', verify: 'OUTCOME_VERIFIED', reconcile: 'RECONCILIATION_REQUIRED', cancel: 'CANCELLED', compensate: 'COMPENSATION_REQUIRED', takeover: 'RECONCILIATION_REQUIRED' };
      const result = await new ShadowExecutionAssurance(repositories).transition(command, command.status, next[action], { actor_id: principal!.actor_id, action, external_reference: body.external_reference, evidence_ids: body.evidence_ids });
      const eventType = next[action] === 'ACKNOWLEDGED' ? 'ACKNOWLEDGED' : next[action] === 'OUTCOME_REPORTED' ? 'OUTCOME_REPORTED' : next[action] === 'OUTCOME_VERIFIED' ? 'OUTCOME_VERIFIED' : next[action] === 'RECONCILIATION_REQUIRED' ? 'RECONCILIATION_REQUIRED' : next[action] === 'COMPENSATION_REQUIRED' ? 'COMPENSATION_STARTED' : 'CORRECTION_RECORDED';
      await repositories.appendEvent(executionEvent(result, eventType, principal!.actor_id, bind!, { action, status: result.status, external_reference: body.external_reference }));
      return { status: 200, body: { data: result, meta: { correlation_id: bind?.correlation_id, contract_version: CONTRACT_VERSION } } };
    });
    if (request.method === 'POST' && url.pathname === '/v1/outcomes') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => { const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id)); const decision = proposal ? await repositories.getKernelDecision(principal!.tenant_id, proposal.proposal_id) : null; let receiptId: string | undefined; if (proposal && decision) { const receipt = new HashLinkedReceiptService().issue(proposal, decision, body as never); receiptId = receipt.receipt_id; await repositories.putReceipt({ ...receipt, tenant_id: principal!.tenant_id }); } await repositories.putOutcome(Object.assign({}, body, { tenant_id: principal!.tenant_id }) as never); await repositories.enqueueOutbox({ outbox_id: `outbox-outcome-${String(body.outcome_id)}`, tenant_id: principal!.tenant_id, dedupe_key: `outcome:${String(body.outcome_id)}`, topic: 'OUTCOME_OBSERVED', aggregate_id: proposal?.incident_id ?? String(body.proposal_id), payload: { outcome_id: String(body.outcome_id), proposal_id: String(body.proposal_id) }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: proposal?.state_version }); if (receiptId) await repositories.enqueueOutbox({ outbox_id: `outbox-receipt-sign-${receiptId}`, tenant_id: principal!.tenant_id, dedupe_key: `receipt-sign:${receiptId}`, topic: 'RECEIPT_SIGN', aggregate_id: receiptId, payload: { receipt_id: receiptId, proposal_id: String(body.proposal_id), state_version: proposal?.state_version }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: proposal?.state_version }); return { status: 201, body: { data: body, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } }; });
    if (request.method === 'POST' && url.pathname === '/v1/break-glass/requests') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => { const capabilities = Array.isArray(body.capabilities) ? body.capabilities.map(String) : []; const resources = Array.isArray(body.resources) ? body.resources.map(String) : []; const duration = Number(body.duration_seconds); const forbidden = ['receipt:write', 'audit:write', 'identity:admin', 'policy:write', 'historical-evidence:mutate']; if (!body.incident_id || !body.justification || !capabilities.length || !resources.length || capabilities.some(capability => forbidden.includes(capability)) || !Number.isFinite(duration) || duration <= 0 || duration > 3600) return failureResult('VALIDATION_FAILED', 'Break-glass requests require an incident, justification, permitted capabilities, resources and a duration no longer than one hour', bind!.correlation_id); const now = new Date().toISOString(); const grant: BreakGlassGrant = { grant_id: `bg-${principal!.tenant_id}-${bind!.idempotency_key}`, tenant_id: principal!.tenant_id, incident_id: String(body.incident_id), requested_by: principal!.actor_id, capabilities, resources, justification: String(body.justification).slice(0, 2000), duration_seconds: duration, status: 'REQUESTED', requested_at: now, review_due_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString() }; await repositories.putBreakGlass(grant); await repositories.appendEvent({ event_id: `${grant.grant_id}:requested`, tenant_id: grant.tenant_id, event_type: 'BREAK_GLASS_REQUESTED', actor_id: principal!.actor_id, actor_type: principal!.actor_type, scope_id: 'break-glass', incident_id: grant.incident_id, occurred_at: now, observed_at: now, available_to_controller_at: now, recorded_at: now, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: currentState.version, state_version_after: currentState.version, policy_version: 'BREAK-GLASS-v1', payload: { grant_id: grant.grant_id, capabilities, resources, justification: grant.justification, duration_seconds: duration }, payload_hash: stableHash(grant), previous_record_hash: 'sha256:break-glass', signature: 'simulated', simulated: true }); await repositories.enqueueOutbox({ outbox_id: `${grant.grant_id}:notify`, tenant_id: grant.tenant_id, dedupe_key: `break-glass-notify:${grant.grant_id}`, topic: 'BREAK_GLASS_NOTIFICATION', aggregate_id: grant.incident_id, payload: { grant_id: grant.grant_id, notify: ['security', 'tenant-administrators'] }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: currentState.version }); return { status: 201, body: { data: grant, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } }; });
    if (request.method === 'POST' && /^\/v1\/break-glass\/[^/]+\/use$/.test(url.pathname)) return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => { const grantId = url.pathname.split('/')[3]; const grant = await repositories.getBreakGlass(principal!.tenant_id, grantId); const capability = String(body.capability ?? ''); const resource = String(body.resource ?? ''); if (!grant || grant.requested_by !== principal!.actor_id || grant.status !== 'ACTIVE' || !grant.expires_at || Date.parse(grant.expires_at) <= Date.now() || !grant.capabilities.includes(capability) || !grant.resources.includes(resource)) return failureResult('PERMISSION_DENIED', 'Break-glass grant is expired, revoked or outside its scope', bind!.correlation_id); const now = new Date().toISOString(); await repositories.appendEvent({ event_id: `${grant.grant_id}:use:${bind!.idempotency_key}`, tenant_id: grant.tenant_id, event_type: 'BREAK_GLASS_USED', actor_id: principal!.actor_id, actor_type: principal!.actor_type, scope_id: resource, incident_id: grant.incident_id, occurred_at: now, observed_at: now, available_to_controller_at: now, recorded_at: now, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: currentState.version, state_version_after: currentState.version, policy_version: 'BREAK-GLASS-v1', payload: { grant_id: grant.grant_id, capability, resource }, payload_hash: stableHash({ grantId, capability, resource }), previous_record_hash: 'sha256:break-glass', signature: 'simulated', simulated: true }); return { status: 200, body: { data: { grant_id: grantId, capability, resource, recorded: true }, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } }; });
    const tenantId = principal?.tenant_id ?? bind?.tenant_id;
    if (request.method === 'POST' && /^\/v1\/outbox\/[^/]+\/requeue$/.test(url.pathname)) {
      if (!principal?.roles.some(role => role === 'auditor' || role === 'investigator' || role === 'administrator')) return failure(response, 'PERMISSION_DENIED', 'Governed outbox replay requires an auditor, investigator or administrator role');
      const outboxId = url.pathname.split('/').at(-2)!;
      return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
        const requeued = await repositories.requeueOutbox(principal!.tenant_id, outboxId);
        if (!requeued) return failureResult('VALIDATION_FAILED', 'Only a dead-letter message may be requeued', bind?.correlation_id);
        await repositories.appendEvent({ event_id: `requeue-${outboxId}-${bind!.idempotency_key}`, tenant_id: principal!.tenant_id, event_type: 'CORRECTION_RECORDED', actor_id: principal!.actor_id, actor_type: 'HUMAN', scope_id: 'outbox', incident_id: outboxId, occurred_at: bind!.request_timestamp, observed_at: bind!.request_timestamp, available_to_controller_at: bind!.request_timestamp, recorded_at: bind!.request_timestamp, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: 0, state_version_after: 0, policy_version: 'OUTBOX-REPLAY', payload: { outbox_id: outboxId, reason: body.reason ?? 'governed replay' }, payload_hash: 'sha256:requeue', previous_record_hash: 'sha256:requeue', signature: 'simulated', simulated: true });
        return { status: 200, body: { data: { outbox_id: outboxId, status: 'PENDING', audited: true }, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
      });
    }
    if (request.method === 'GET' && url.pathname === '/v1/model-releases') return reply(response, 200, { data: modelReleases, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } });
    if (request.method === 'GET' && url.pathname.startsWith('/v1/model-releases/')) { const parts = url.pathname.split('/'); const release = modelReleases.find(item => item.release_id === parts[3]); if (!release) return failure(response, 'VALIDATION_FAILED', 'Model release not found'); if (parts[4] === 'capabilities') return reply(response, 200, { data: release.capabilities, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); if (parts[4] === 'evaluations') return reply(response, 200, { data: release.capabilities.flatMap(capability => capability.evaluation_ids.map(id => ({ evaluation_id: id, result: capability.evaluation_results, status: capability.qualification_status }))), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); return reply(response, 200, { data: release, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); }
    const releaseTransitionMatch = url.pathname.match(/^\/v1\/institution-releases\/([^/]+)\/transition$/);
    if (request.method === 'POST' && releaseTransitionMatch) {
      const releaseId = releaseTransitionMatch[1];
      const nextState = String(body.next_state ?? '') as never;
      const actorType = principal!.actor_type === 'SYSTEM' ? 'SYSTEM' : principal!.actor_type === 'AGENT' ? 'WORKER' : 'HUMAN';
      try {
        const result = await institutionTransitionService.transition({
          tenant_id: principal!.tenant_id, institution_id: String(body.institution_id ?? ''), release_id: releaseId,
          expected_state: String(body.expected_state ?? '') as never, expected_version: Number(body.expected_version), next_state: nextState,
          actor_id: principal!.actor_id, actor_type: actorType, reason: String(body.reason ?? ''),
          correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, idempotency_key: bind!.idempotency_key,
          occurred_at: bind!.request_timestamp, gate: body.gate as never,
        });
        return reply(response, 200, { data: result, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } });
      } catch (error) {
        const code = error instanceof Error && error.message.startsWith('TEST_FAULT_') ? 'INTERNAL_ERROR' : error instanceof Error && (error.message === 'STATE_STALE' || error.message.startsWith('INVALID_')) ? 'STATE_STALE' : 'VALIDATION_FAILED';
        return failure(response, code, error instanceof Error ? error.message : 'Transition failed', bind?.correlation_id);
      }
    }
    const releaseReadMatch = url.pathname.match(/^\/v1\/institution-releases\/([^/]+)$/);
    if (request.method === 'GET' && releaseReadMatch) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => { const release = await repositories.getInstitutionRelease(tenantId!, releaseReadMatch[1]); if (!release) return reply(response, 404, { error: { code: 'NOT_FOUND', message: 'Institution release not found' } }); return reply(response, 200, { data: release, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); });
    const sourceMatch = url.pathname.match(/^\/v1\/institutions\/([^/]+)\/sources(?:\/([^/]+)\/versions)?$/);
    if (sourceMatch && request.method === 'POST' && sourceMatch[2] === undefined) return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const institutionId = sourceMatch[1];
      const sourceId = String(body.source_id ?? '');
      const sourceVersion = String(body.source_version ?? '');
      const ownerId = principal!.actor_id;
      const effectiveFrom = String(body.effective_from ?? '');
      const contentHash = String(body.content_hash ?? '');
      if (!sourceId || !sourceVersion || !effectiveFrom || !contentHash || !body.provenance || !body.sensitivity) return failureResult('VALIDATION_FAILED', 'Source id, version, provenance, sensitivity, effective_from and content_hash are required', bind?.correlation_id);
      const source: InstitutionSourceRecord = { tenant_id: principal!.tenant_id, institution_id: institutionId, source_id: sourceId, source_version: sourceVersion, owner_id: ownerId, provenance: String(body.provenance), sensitivity: String(body.sensitivity), effective_from: effectiveFrom, effective_to: body.effective_to ? String(body.effective_to) : undefined, content_hash: contentHash, classification_status: String(body.classification_status ?? 'PENDING'), ingestion_timestamp: bind!.request_timestamp, payload: typeof body.payload === 'object' && body.payload !== null ? body.payload as Record<string, unknown> : {} };
      const inserted = await repositories.putInstitutionSource(source);
      if (!inserted) return failureResult('VALIDATION_FAILED', 'Source version already exists', bind?.correlation_id);
      await repositories.enqueueOutbox({ outbox_id: `compile-source-${principal!.tenant_id}-${institutionId}-${sourceId}-${sourceVersion}`, tenant_id: principal!.tenant_id, dedupe_key: `institution-compile:${institutionId}:${sourceId}:${sourceVersion}`, topic: 'INSTITUTION_COMPILE_REQUESTED', aggregate_id: institutionId, payload: { institution_id: institutionId, source_id: sourceId, source_version: sourceVersion, content_hash: contentHash, requested_by: principal!.actor_id }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: 0 });
      return { status: 201, body: { data: source, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
    });
    if (sourceMatch && request.method === 'GET') return await runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => {
      const institutionId = sourceMatch[1]; const sourceId = sourceMatch[2]; const data = sourceId ? await repositories.listInstitutionSourceVersions(principal!.tenant_id, institutionId, sourceId) : await repositories.listInstitutionSources(principal!.tenant_id, institutionId);
      return reply(response, 200, { data, meta: { correlation_id: request.headers['x-correlation-id'] ?? 'read', contract_version: CONTRACT_VERSION } });
    });
    if (request.method === 'GET' && url.pathname === '/v1/institution-compilations') return await runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => {
      const institutionId = String(url.searchParams.get('institution_id') ?? '');
      if (!institutionId) return failure(response, 'VALIDATION_FAILED', 'institution_id is required');
      return reply(response, 200, { data: await repositories.getInstitutionCompilationStatus(principal!.tenant_id, institutionId), meta: { correlation_id: request.headers['x-correlation-id'] ?? 'read', contract_version: CONTRACT_VERSION } });
    });
    const compilationMatch = url.pathname.match(/^\/v1\/institution-compilations\/([^/]+)$/);
    if (request.method === 'POST' && url.pathname === '/v1/institution-compilations') return await transactionResponse(runtimeDependencies.repositories, principal!.tenant_id, response, async repositories => {
      const institutionId = String(body.institution_id ?? '');
      if (!institutionId) return failureResult('VALIDATION_FAILED', 'institution_id is required', bind?.correlation_id);
      const requestKey = `institution-compile-request:${institutionId}:${bind!.idempotency_key}`;
      const queued = await repositories.enqueueOutbox({ outbox_id: `compile-request-${principal!.tenant_id}-${institutionId}-${bind!.idempotency_key}`, tenant_id: principal!.tenant_id, dedupe_key: requestKey, topic: 'INSTITUTION_COMPILE_REQUESTED', aggregate_id: institutionId, payload: { institution_id: institutionId, requested_by: principal!.actor_id }, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version: 0 });
      return { status: queued ? 202 : 200, body: { data: { institution_id: institutionId, queued, status: 'COMPILATION_REQUESTED' }, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } } };
    });
    if (request.method === 'GET' && compilationMatch) return await runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => {
      const institutionId = String(url.searchParams.get('institution_id') ?? '');
      if (!institutionId) return failure(response, 'VALIDATION_FAILED', 'institution_id is required');
      const candidate = await repositories.getInstitutionCandidate(principal!.tenant_id, institutionId, compilationMatch[1]);
      if (!candidate) return reply(response, 404, { error: { code: 'NOT_FOUND', message: 'Institution compilation not found' } });
      return reply(response, 200, { data: candidate, meta: { correlation_id: request.headers['x-correlation-id'] ?? 'read', contract_version: CONTRACT_VERSION } });
    });
    if (request.method === 'GET' && url.pathname.startsWith('/v1/reconstructions/') && !principal?.roles.some(role => role === 'auditor' || role === 'investigator')) return failure(response, 'PERMISSION_DENIED', 'Reconstruction access requires an auditor or investigator role');
    if (request.method === 'GET' && url.pathname.startsWith('/v1/state/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await state(repositories, tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: request.headers['x-correlation-id'] ?? 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/incidents/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: { incident_id: url.pathname.split('/').at(-1), state: await state(repositories, tenantId!, 'memphis-fulfillment'), proposal_ids: [] }, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/receipts/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => { const receipt = await repositories.getReceipt(tenantId!, url.pathname.split('/').at(-1) ?? ''); if (!receipt) return reply(response, 404, { error: { code: 'NOT_FOUND', message: 'Receipt not found' } }); if (receipt.signature_status === 'SIGNED') { const unsigned = { ...receipt, signature: '', signature_status: 'SIGNATURE_PENDING' as const }; delete (unsigned as Record<string, unknown>).digest; delete (unsigned as Record<string, unknown>).algorithm; delete (unsigned as Record<string, unknown>).key_id; delete (unsigned as Record<string, unknown>).key_version; delete (unsigned as Record<string, unknown>).signed_at; const valid = await runtimeDependencies.receiptSigner.verify(canonicalize(unsigned), receipt.signature, receipt.key_id ?? '', receipt.key_version); if (!valid) return failure(response, 'INTEGRITY_FAILED', 'Receipt signature verification failed'); } return reply(response, 200, { data: receipt, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); });
    if (request.method === 'GET' && url.pathname.startsWith('/v1/proposals/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getProposal(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/executions/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => { const commandId = url.pathname.split('/')[3] ?? ''; const command = await repositories.getExecution(tenantId!, commandId); if (!command) return reply(response, 404, { error: { code: 'NOT_FOUND', message: 'Execution command not found' } }); return reply(response, 200, { data: { command, transitions: await repositories.listExecutionTransitions(tenantId!, commandId) }, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); });
    if (request.method === 'GET' && url.pathname.startsWith('/v1/decisions/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getKernelDecision(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/outcomes/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getOutcome(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/break-glass/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => { const grant = await repositories.getBreakGlass(tenantId!, url.pathname.split('/').at(-1) ?? ''); if (!grant) return reply(response, 404, { error: { code: 'NOT_FOUND', message: 'Break-glass grant not found' } }); if (grant.status === 'ACTIVE' && grant.expires_at && Date.parse(grant.expires_at) <= Date.now()) { const expired = { ...grant, status: 'EXPIRED' as const }; await repositories.updateBreakGlass(expired); const now = new Date().toISOString(); await repositories.appendEvent({ event_id: `${grant.grant_id}:expired`, tenant_id: grant.tenant_id, event_type: 'BREAK_GLASS_EXPIRED', actor_id: 'system', actor_type: 'SYSTEM', scope_id: 'break-glass', incident_id: grant.incident_id, occurred_at: now, observed_at: now, available_to_controller_at: now, recorded_at: now, correlation_id: 'break-glass-expiry', trace_id: 'break-glass-expiry', state_version_before: 0, state_version_after: 0, policy_version: 'BREAK-GLASS-v1', payload: { grant_id: grant.grant_id }, payload_hash: stableHash(expired), previous_record_hash: 'sha256:break-glass', signature: 'simulated', simulated: true }); return reply(response, 200, { data: expired, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); } return reply(response, 200, { data: grant, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); });
    if (request.method === 'POST' && /^\/v1\/reconstructions\/[^/]+\/export$/.test(url.pathname)) return await transactionResponse(runtimeDependencies.repositories, tenantId!, response, async repositories => { const incidentId = url.pathname.split('/')[3] ?? ''; if (body.legal_hold === false) return failureResult('PERMISSION_DENIED', 'Export blocked by retention or legal-hold policy', bind?.correlation_id); const service = new ForensicReconstructionService(repositories, runtimeDependencies.receiptSigner); const pkg = await service.exportPackage(tenantId!, { caseId: incidentId, cutoff: typeof body.cutoff === 'string' ? body.cutoff : undefined, offset: typeof body.offset === 'number' ? body.offset : undefined, includeRestricted: body.include_restricted === true, legalHold: true }); return { status: 200, body: { data: pkg, meta: { correlation_id: bind?.correlation_id, contract_version: CONTRACT_VERSION } } }; });
    if (request.method === 'GET' && url.pathname.startsWith('/v1/reconstructions/')) return await runtimeDependencies.repositories.transaction(tenantId!, async repositories => { const incidentId = url.pathname.split('/').at(-1) ?? ''; const service = new ForensicReconstructionService(repositories, runtimeDependencies.receiptSigner); return reply(response, 200, { data: await service.reconstruct(tenantId!, { caseId: incidentId, legalHold: true }), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); });
    return failure(response, 'VALIDATION_FAILED', 'Route not found');
    } catch (error) {
      if (error instanceof StateConflictError) return failure(response, 'STATE_STALE', error.message, error.correlationId);
      console.error('Control Plane request failed', error);
      return failure(response, 'INTERNAL_ERROR', 'Internal server error');
    }
  });
}


