import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { CONTRACT_VERSION, openApiDocument, validateBinding, type RequestBinding, type C1ModelRelease } from '../../../packages/contracts/src/index.js';
import { DeterministicEvidenceAdmission } from '../../../packages/platform-core/src/evidence-admission.js';
import { DeterministicKernel } from '../../../packages/platform-core/src/kernel.js';
import { LogisticsProposalGenerator } from '../../../packages/platform-core/src/proposal-generator.js';
import { ReplayableStateProjector } from '../../../packages/platform-core/src/state-projector.js';
import { HumanReviewGate } from '../../../packages/platform-core/src/human-review.js';
import { ShadowEvaluator } from '../../../packages/platform-core/src/shadow-evaluator.js';
import { SimulatedIdentityVerifier, type IdentityVerifier } from '../../../packages/platform-core/src/auth.js';
import { InMemoryPlatformRepositories } from '../../../packages/platform-core/src/repositories.js';
import { HashLinkedReceiptService } from '../../../packages/platform-core/src/receipt-service.js';
import { KmsReceiptCustody, type ReceiptSigner } from '../../../packages/platform-core/src/receipt-custody.js';
import { assertRuntimeProfile, type RuntimeDependencies, type RuntimeProfile } from './runtime.js';

const repositories = new InMemoryPlatformRepositories();
const state = async (repositories: RuntimeDependencies['repositories'], tenantId: string, scopeId: string) => new ReplayableStateProjector().project(await repositories.getEvents(tenantId, undefined).then(events => events.filter(event => event.scope_id === scopeId)));
const modelReleases: C1ModelRelease[] = [{ release_id: 'c1-shadow-0.9.1', model_hash: 'sha256:c1-shadow-demo', adapter_hash: 'sha256:no-adapter', actionnet_version: 'actionnet-v0.4', status: 'QUALIFIED_SHADOW', capabilities: [{ capability_id: 'c1.institutional-assessment', name: 'Institutional situation assessment', description: 'Diagnoses operational changes and identifies affected commitments.', release_id: 'c1-shadow-0.9.1', model_hash: 'sha256:c1-shadow-demo', adapter_hash: 'sha256:no-adapter', actionnet_version: 'actionnet-v0.4', qualification_status: 'QUALIFIED_SHADOW', qualified_workflows: ['logistics.recovery'], permitted_operating_modes: ['SHADOW'], input_schema: 'InstitutionalSituation.v1', output_schema: 'Assessment.v1', required_context: ['state', 'evidence', 'commitments', 'authority'], evaluation_ids: ['eval-transfer-seed-1', 'eval-transfer-seed-2'], evaluation_results: { mean: 0.8594, seed_1: 0.8875, seed_2: 0.8313 }, safety_constraints: ['No authority grant', 'No execution credentials', 'Citations required'], unsupported_conditions: ['Unadmitted evidence', 'Missing state version'], latency_limit_ms: 10000, cost_limit: 'shadow-only', fallback_behavior: 'ABSTAIN and request human review', approval_authority: 'Institutional Kernel', qualified_at: '2026-09-24T00:00:00Z', expires_at: '2026-12-23T00:00:00Z' }] }];
const json = (request: IncomingMessage) => new Promise<Record<string, unknown>>((resolve, reject) => { let body = ''; request.on('data', chunk => { body += chunk; }); request.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('invalid json')); } }); });
const reply = (response: ServerResponse, status: number, body: unknown) => { response.statusCode = status; response.setHeader('content-type', 'application/json'); response.end(JSON.stringify(body)); };
const failure = (response: ServerResponse, code: string, message: string, correlation_id = 'unknown') => reply(response, code === 'INTERNAL_ERROR' ? 500 : code === 'VALIDATION_FAILED' ? 400 : code === 'PERMISSION_DENIED' ? 403 : code === 'STATE_STALE' ? 409 : 422, { error: { code, message, correlation_id } });
class StateConflictError extends Error { constructor(public readonly correlationId: string) { super('State changed while projecting the event'); } }
const binding = (body: Record<string, unknown>) => body.binding as RequestBinding | undefined;
const validateRequest = (body: Record<string, unknown>) => validateBinding(binding(body));

export type ControlPlaneServerOptions = Partial<RuntimeDependencies> & { profile?: RuntimeProfile; identityVerifier?: IdentityVerifier; receiptSigner?: ReceiptSigner; corsOrigin?: string };
export function createControlPlaneServer(options: ControlPlaneServerOptions = {}) {
  const profile = options.profile ?? 'LOCAL';
  const identityVerifier = options.identityVerifier ?? new SimulatedIdentityVerifier({ tenant_id: 'meridian-demo', actor_id: 'operator-01', actor_type: 'HUMAN', roles: ['operator'], expires_at: '2099-01-01T00:00:00Z' });
  const runtimeDependencies: RuntimeDependencies = { repositories: options.repositories ?? repositories, identityVerifier, receiptSigner: options.receiptSigner ?? new KmsReceiptCustody(), tenantIsolation: options.tenantIsolation ?? profile === 'LOCAL', auditLogging: options.auditLogging ?? profile === 'LOCAL', signingKeyMode: options.signingKeyMode ?? 'DEVELOPMENT' };
  assertRuntimeProfile(profile, runtimeDependencies);
  return createServer(async (request, response) => {
    try {
    const origin = request.headers.origin;
    if (origin && origin === options.corsOrigin) response.setHeader('access-control-allow-origin', origin);
    response.setHeader('vary', 'Origin');
    if (request.method === 'OPTIONS') { response.setHeader('access-control-allow-headers', 'authorization,content-type,x-correlation-id,x-trace-id'); response.setHeader('access-control-allow-methods', 'GET,POST,OPTIONS'); return reply(response, 204, null); }
    const url = new URL(request.url ?? '/', 'http://localhost');
    if (request.method === 'GET' && url.pathname === '/openapi.json') return reply(response, 200, openApiDocument());
    let body: Record<string, unknown> = {};
    try { if (request.method === 'POST') body = await json(request); } catch { return failure(response, 'VALIDATION_FAILED', 'Request body must be valid JSON'); }
    const bind = binding(body);
    if (request.method === 'GET' && url.pathname === '/healthz') return reply(response, 200, { status: 'ok', profile });
    if (request.method === 'GET' && url.pathname === '/readyz') return reply(response, profile === 'LOCAL' || (runtimeDependencies.tenantIsolation && runtimeDependencies.auditLogging) ? 200 : 503, { status: profile === 'LOCAL' ? 'ready-simulated' : 'ready' });
    const principal = await runtimeDependencies.identityVerifier.verify(request);
    const authenticatedRoute = url.pathname.startsWith('/v1/');
    if (authenticatedRoute && !principal) return reply(response, 401, { error: { code: 'AUTHENTICATION_REQUIRED', message: 'Authentication is required', correlation_id: request.headers['x-correlation-id'] ?? 'unknown' } });
    if (authenticatedRoute && principal?.active === false) return failure(response, 'PERMISSION_DENIED', 'Actor is inactive');
    if (request.method === 'POST' && principal && bind && (bind.tenant_id !== principal.tenant_id || bind.actor_id !== principal.actor_id)) return failure(response, 'PERMISSION_DENIED', 'Request identity does not match verified identity', principal.actor_id);
    if (request.method === 'POST' && (!validateRequest(body) || bind?.contract_version !== CONTRACT_VERSION)) return failure(response, 'VALIDATION_FAILED', 'Required request binding is missing or invalid', bind?.correlation_id);
    const currentState = bind ? await runtimeDependencies.repositories.transaction(principal!.tenant_id, repositories => state(repositories, principal!.tenant_id, String(body.scope_id ?? 'memphis-fulfillment'))) : { version: 141, values: {} };
    if (request.method === 'POST' && url.pathname !== '/v1/events' && bind?.expected_state_version !== undefined && bind.expected_state_version !== currentState.version) return failure(response, 'STATE_STALE', 'Expected state version is stale', bind.correlation_id);
    if (request.method === 'POST' && url.pathname === '/v1/events') {
      return runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => {
        const transactionState = await state(repositories, principal!.tenant_id, String(body.scope_id ?? 'memphis-fulfillment'));
        const event = { event_id: String(body.event_id ?? `evt-${Date.now()}`), tenant_id: principal!.tenant_id, event_type: 'OBSERVATION_RECEIVED' as const, actor_id: bind!.actor_id, actor_type: 'CONNECTOR' as const, scope_id: String(body.scope_id ?? 'memphis-fulfillment'), incident_id: String(body.incident_id ?? 'INC-1042'), occurred_at: bind!.request_timestamp, observed_at: bind!.request_timestamp, available_to_controller_at: bind!.request_timestamp, recorded_at: bind!.request_timestamp, correlation_id: bind!.correlation_id, trace_id: bind!.trace_id, state_version_before: transactionState.version, state_version_after: transactionState.version, policy_version: 'POL-LOG-07 v18', payload: (body.payload ?? {}) as Record<string, unknown>, payload_hash: 'sha256:api', previous_record_hash: 'sha256:api', signature: 'simulated', simulated: true as const };
        const operationKey = `POST:/v1/events:${bind!.idempotency_key}`;
        const existing = await repositories.getIdempotency(principal!.tenant_id, operationKey);
        if (existing !== undefined) return reply(response, 200, { data: existing, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } });
        if (bind!.expected_state_version !== undefined && bind!.expected_state_version !== transactionState.version) return failure(response, 'STATE_STALE', 'Expected state version is stale', bind!.correlation_id);
        const idempotency = await repositories.claimIdempotency(principal!.tenant_id, operationKey, event);
        if (!idempotency.claimed) return reply(response, 200, { data: idempotency.response, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } });
        if (bind!.expected_state_version !== undefined && bind!.expected_state_version !== transactionState.version) return failure(response, 'STATE_STALE', 'Expected state version is stale', bind!.correlation_id);
        const appended = await repositories.appendEvent(event);
        if (!appended) return reply(response, 200, { data: event, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } });
        const projectedEvent = { ...event, event_id: `${event.event_id}:state`, event_type: 'STATE_PROJECTED' as const, actor_id: 'control-plane', actor_type: 'SYSTEM' as const, state_version_before: transactionState.version, state_version_after: transactionState.version + 1, causation_id: event.event_id, payload: { capacity_units: Number((event.payload as Record<string, unknown>).capacity_units ?? 260), commitments_at_risk: Number((event.payload as Record<string, unknown>).commitments_at_risk ?? 4) } };
        await repositories.appendEvent(projectedEvent);
        const projected = await state(repositories, bind!.tenant_id, event.scope_id);
        const projectedVersion = projected.version;
        const persisted = await repositories.putState({ tenant_id: bind!.tenant_id, incident_id: event.incident_id, scope_id: event.scope_id, state_version: projectedVersion, status: 'OPEN', values: projected.values }, transactionState.version);
        if (!persisted) throw new StateConflictError(bind!.correlation_id);
        return reply(response, 201, { data: { ...event, state_version_after: projectedVersion }, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } });
      });
    }
    if (request.method === 'POST' && url.pathname === '/v1/proposals') return runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => { const transactionState = await state(repositories, principal!.tenant_id, String(body.scope_id ?? 'memphis-fulfillment')); if (bind!.expected_state_version !== undefined && bind!.expected_state_version !== transactionState.version) return failure(response, 'STATE_STALE', 'Expected state version is stale', bind!.correlation_id); const evidence = new DeterministicEvidenceAdmission().admit({ event: 'capacity_disruption' }); for (const record of evidence) await repositories.putEvidence({ ...record, tenant_id: principal!.tenant_id }); const proposal = new LogisticsProposalGenerator().create(transactionState, evidence); await repositories.putIncident({ tenant_id: principal!.tenant_id, incident_id: proposal.incident_id, scope_id: String(body.scope_id ?? 'memphis-fulfillment'), state_version: transactionState.version, status: 'OPEN' }); await repositories.putProposal({ ...proposal, tenant_id: principal!.tenant_id }); return reply(response, 201, { data: proposal, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } }); });
    if (request.method === 'POST' && url.pathname === '/v1/reviews') return runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => { const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id)); if (!proposal) return failure(response, 'VALIDATION_FAILED', 'Proposal not found', bind?.correlation_id); const transactionState = await state(repositories, principal!.tenant_id, String(body.scope_id ?? 'memphis-fulfillment')); const decision = new HumanReviewGate().reevaluate(proposal, body.approved === true, transactionState.version, 30000); await repositories.putKernelDecision({ ...decision, tenant_id: principal!.tenant_id, recorded_at: bind!.request_timestamp }); await repositories.putReview({ tenant_id: principal!.tenant_id, review_id: `review-${proposal.proposal_id}`, proposal_id: proposal.proposal_id, actor_id: bind!.actor_id, approved: body.approved === true, recorded_at: bind!.request_timestamp }); return reply(response, 200, { data: decision, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } }); });
    if (request.method === 'POST' && url.pathname === '/v1/shadow-evaluations') return runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => { const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id)); if (!proposal) return failure(response, 'VALIDATION_FAILED', 'Proposal not found', bind?.correlation_id); const shadow = new ShadowEvaluator().record(proposal); await repositories.putShadow({ proposal_id: shadow.proposal_id, recorded_at: shadow.recommendation_recorded_at, executed: false, credentials: 'NONE', tenant_id: principal!.tenant_id }); return reply(response, 201, { data: shadow, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } }); });
    if (request.method === 'POST' && url.pathname === '/v1/outcomes') return runtimeDependencies.repositories.transaction(principal!.tenant_id, async repositories => { const proposal = await repositories.getProposal(principal!.tenant_id, String(body.proposal_id)); const decision = proposal ? await repositories.getKernelDecision(principal!.tenant_id, proposal.proposal_id) : null; if (proposal && decision) { const receipt = new HashLinkedReceiptService().issue(proposal, decision, body as never); await repositories.putReceipt({ ...receipt, tenant_id: principal!.tenant_id }); } await repositories.putOutcome(Object.assign({}, body, { tenant_id: principal!.tenant_id }) as never); return reply(response, 201, { data: body, meta: { correlation_id: bind!.correlation_id, contract_version: CONTRACT_VERSION } }); });
    const tenantId = principal?.tenant_id ?? bind?.tenant_id;
    if (request.method === 'GET' && url.pathname === '/v1/model-releases') return reply(response, 200, { data: modelReleases, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } });
    if (request.method === 'GET' && url.pathname.startsWith('/v1/model-releases/')) { const parts = url.pathname.split('/'); const release = modelReleases.find(item => item.release_id === parts[3]); if (!release) return failure(response, 'VALIDATION_FAILED', 'Model release not found'); if (parts[4] === 'capabilities') return reply(response, 200, { data: release.capabilities, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); if (parts[4] === 'evaluations') return reply(response, 200, { data: release.capabilities.flatMap(capability => capability.evaluation_ids.map(id => ({ evaluation_id: id, result: capability.evaluation_results, status: capability.qualification_status }))), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); return reply(response, 200, { data: release, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); }
    if (request.method === 'GET' && url.pathname.startsWith('/v1/reconstructions/') && !principal?.roles.some(role => role === 'auditor' || role === 'investigator')) return failure(response, 'PERMISSION_DENIED', 'Reconstruction access requires an auditor or investigator role');
    if (request.method === 'GET' && url.pathname.startsWith('/v1/state/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await state(repositories, tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: request.headers['x-correlation-id'] ?? 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/incidents/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: { incident_id: url.pathname.split('/').at(-1), state: await state(repositories, tenantId!, 'memphis-fulfillment'), proposal_ids: [] }, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/receipts/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getReceipt(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/proposals/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getProposal(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/decisions/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getKernelDecision(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/outcomes/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => reply(response, 200, { data: await repositories.getOutcome(tenantId!, url.pathname.split('/').at(-1) ?? ''), meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }));
    if (request.method === 'GET' && url.pathname.startsWith('/v1/reconstructions/')) return runtimeDependencies.repositories.transaction(tenantId!, async repositories => { const incidentId = url.pathname.split('/').at(-1) ?? ''; const events = await repositories.getEvents(tenantId!, incidentId); if (!events.length) return failure(response, 'PERMISSION_DENIED', 'Incident is not available in the authenticated tenant'); return reply(response, 200, { data: { incident_id: incidentId, events, state: await state(repositories, tenantId!, 'memphis-fulfillment') }, meta: { correlation_id: 'read', contract_version: CONTRACT_VERSION } }); });
    return failure(response, 'VALIDATION_FAILED', 'Route not found');
    } catch (error) {
      if (error instanceof StateConflictError) return failure(response, 'STATE_STALE', error.message, error.correlationId);
      console.error('Control Plane request failed', error);
      return failure(response, 'INTERNAL_ERROR', 'Internal server error');
    }
  });
}


