export type ActorType = 'HUMAN' | 'AGENT' | 'WORKER' | 'SYSTEM' | 'KERNEL' | 'CONNECTOR';
export type LifecycleEvent = 'OBSERVATION_RECEIVED' | 'EVIDENCE_ADMITTED' | 'STATE_PROJECTED' | 'MODEL_INVOKED' | 'PROPOSAL_CREATED' | 'KERNEL_DECIDED' | 'HUMAN_REVIEWED' | 'SHADOW_RECOMMENDATION_RECORDED' | 'OUTCOME_OBSERVED' | 'OUTCOME_VERIFIED' | 'RECEIPT_ISSUED' | 'CORRECTION_RECORDED' | 'BREAK_GLASS_REQUESTED' | 'BREAK_GLASS_APPROVED' | 'BREAK_GLASS_ACTIVATED' | 'BREAK_GLASS_USED' | 'BREAK_GLASS_EXPIRED' | 'BREAK_GLASS_REVOKED' | 'DISPATCH_REQUESTED' | 'DISPATCHED' | 'DISPATCH_REJECTED' | 'DISPATCH_FAILED' | 'ACKNOWLEDGED' | 'OUTCOME_REPORTED' | 'RECONCILIATION_REQUIRED' | 'COMPENSATION_STARTED' | 'HUMAN_TAKEOVER' | 'KMS_KEY_ROTATED' | 'INSTITUTION_RELEASE_TRANSITIONED';
export type KernelDisposition = 'ALLOW' | 'DENY' | 'ABSTAIN' | 'ESCALATE' | 'REVISE' | 'REASSIGN' | 'APPROVAL_REQUIRED';

export interface EventEnvelope<T = Record<string, unknown>> {
  event_id: string; tenant_id: string; event_type: LifecycleEvent; actor_id: string; actor_type: ActorType;
  scope_id: string; incident_id: string; occurred_at: string; observed_at: string; available_to_controller_at: string; recorded_at: string;
  correlation_id: string; causation_id?: string; trace_id: string; state_version_before: number; state_version_after: number;
  policy_version: string; model_release?: string; payload: T; payload_hash: string; previous_record_hash: string; signature: string; simulated: true;
}
export interface EvidenceRecord { evidence_id: string; status: 'verified' | 'observed' | 'reported' | 'inferred' | 'missing' | 'restricted' | 'disputed'; source: string; version: string; citation_text: string; }
export interface DecisionContext { tenant_id: string; incident_id: string; state_version: number; state_hash: string; evidence_versions: Record<string, string>; policy_version: string; authority_version: string; mandate_version: string; commitment_version: string; c1_release: string; adapter_version: string; actionnet_version: string; domain_pack_version: string; capability_id: string; operating_mode: 'SHADOW' | 'ASSISTED' | 'PRODUCTION'; }
export interface ActionProposal { proposal_id: string; incident_id: string; objective: string; actions: string[]; modeled_cost: number; commitments_protected: number; assumptions: string[]; citations: string[]; state_version: number; policy_version: string; status: 'DRAFT' | 'PENDING_KERNEL' | 'REVIEW_REQUIRED' | 'SHADOW_RECORDED'; proposal_hash?: string; context?: DecisionContext; }
export interface KernelDecision { decision_id: string; proposal_id: string; disposition: KernelDisposition; reason_codes: string[]; required_approval: boolean; evaluated_at: string; state_version: number; policy_version: string; proposal_hash?: string; review_id?: string; simulated: true; }
export interface OutcomeRecord { outcome_id: string; proposal_id: string; observed_at: string; recovery_time: string; actual_cost: number; commitments_protected: number; evidence_ids: string[]; verification_status: 'PENDING' | 'VERIFIED' | 'DISPUTED'; }
export type ExecutionStatus = 'DISPATCH_PENDING' | 'DISPATCHED' | 'ACKNOWLEDGED' | 'OUTCOME_REPORTED' | 'OUTCOME_VERIFIED' | 'COMPLETED' | 'DISPATCH_REJECTED' | 'DISPATCH_FAILED' | 'OUTCOME_UNKNOWN' | 'RECONCILIATION_REQUIRED' | 'PARTIALLY_COMPLETED' | 'COMPENSATION_REQUIRED' | 'CANCELLED' | 'EXPIRED';
export interface ExecutionCommand { command_id: string; tenant_id?: string; incident_id: string; proposal_id: string; status: ExecutionStatus; command_hash: string; authorization_id: string; proposal_hash: string; state_version: number; external_idempotency_key: string; connector: string; resource: string; credential_scope: string; credential_expires_at?: string; external_reference?: string; dispatch_requested_at: string; dispatched_at?: string; acknowledged_at?: string; outcome_reported_at?: string; outcome_verified_at?: string; expires_at: string; acknowledgement_status?: 'PENDING' | 'RECEIVED' | 'MISSING' | 'DUPLICATE'; outcome_verification?: 'PENDING' | 'VERIFIED' | 'DISPUTED' | 'UNKNOWN'; actual_cost?: number; baseline_estimate?: number; attributed_benefit?: number; uncertainty?: string; compensation_command_id?: string; takeover_actor_id?: string; }
export type ReceiptSignatureStatus = 'SIGNATURE_PENDING' | 'SIGNED' | 'SIGNATURE_FAILED';
export interface DecisionReceipt { receipt_id: string; incident_id: string; proposal_id: string; kernel_decision_id: string; human_reviewed: boolean; shadow_only: true; outcome_id?: string; event_ids: string[]; receipt_hash: string; signature: string; simulated: true; proposal_hash?: string; signature_status?: ReceiptSignatureStatus; digest?: string; algorithm?: string; key_id?: string; key_version?: string; signed_at?: string; evidence_versions?: Record<string, string>; state_version?: number; model_release?: string; policy_version?: string; authority_version?: string; }
export type BreakGlassStatus = 'REQUESTED' | 'APPROVED' | 'ACTIVE' | 'EXPIRED' | 'REVOKED' | 'REVIEW_REQUIRED';
export interface BreakGlassGrant { grant_id: string; tenant_id: string; incident_id: string; requested_by: string; capabilities: string[]; resources: string[]; justification: string; duration_seconds: number; status: BreakGlassStatus; requested_at: string; approved_at?: string; activated_at?: string; expires_at?: string; revoked_at?: string; approved_by?: string; review_due_at?: string; }
export type C1CapabilityStatus = 'INTENDED' | 'EXPERIMENTAL' | 'RESEARCH_SUPPORTED' | 'QUALIFIED_SHADOW' | 'QUALIFIED_ASSISTED' | 'QUALIFIED_PRODUCTION' | 'SUSPENDED' | 'RETIRED';
export interface C1CapabilityManifest { capability_id: string; name: string; description: string; release_id: string; model_hash: string; adapter_hash: string; actionnet_version: string; qualification_status: C1CapabilityStatus; qualified_workflows: string[]; permitted_operating_modes: string[]; input_schema: string; output_schema: string; required_context: string[]; evaluation_ids: string[]; evaluation_results: Record<string, unknown>; safety_constraints: string[]; unsupported_conditions: string[]; latency_limit_ms: number; cost_limit: string; fallback_behavior: string; approval_authority: string; qualified_at: string; expires_at: string; }
export interface C1ModelRelease { release_id: string; model_hash: string; adapter_hash: string; actionnet_version: string; status: C1CapabilityStatus; capabilities: C1CapabilityManifest[]; }
export * from './api.js';
