import { useEffect, useRef, useState } from 'react';
import { Activity as ActivityIcon, ArrowDownToLine, ArrowLeft, ArrowUpRight, Bell, Boxes, Check, ChevronDown, ChevronRight, CircleHelp, FileCheck2, FlaskConical, LayoutGrid, LockKeyhole, MapPin, Menu, MessageSquareText, Network, PanelLeftClose, Radio, RotateCcw, Search, Settings2, ShieldCheck, Signal, Sparkles, TriangleAlert, TrendingUp, Unplug, X } from 'lucide-react';
import { Badge, DefinitionList, EmptyState, LoadingState, Metric, Modal, Notice, Panel } from './components';
import { incidents, initialReceipts, money, scenarios } from './data';
import { ActorInspector, AssuranceRegisterPage, IncidentQueue, InstitutionBuilder, IntegrationsPage, LocationOverview, OperationsOverview, ReceiptDetails, ReceiptList, ReconstructionPage, ReviewsPage, SettingsAdministration, StatePage, ValueReport } from './Pages';
import Workspace, { ShadowComparison } from './Workspace';
import AskCerebrum from './AskCerebrum';
import type { Activity, Evidence, Page, Plan, Receipt, RecourseRecord, ReviewRecord, Role, Scenario, WorkspaceTab } from './types';
import { controlPlaneClient } from './controlPlaneClient';

const navGroups = [
  { label: 'OPERATE', items: [{ page: 'overview', label: 'Operations Overview', icon: ActivityIcon }, { page: 'queue', label: 'Work Queue', icon: LayoutGrid, count: '3' }, { page: 'reviews', label: 'Human reviews', icon: ShieldCheck, count: '1' }] },
  { label: 'ASSURE', items: [{ page: 'outcomes', label: 'Shadow & outcomes', icon: ActivityIcon }, { page: 'reconstructions', label: 'Reconstructions', icon: ActivityIcon }, { page: 'receipts', label: 'Decision receipts', icon: FileCheck2 }, { page: 'exceptions', label: 'Execution exceptions', icon: TriangleAlert }, { page: 'integrity', label: 'Integrity status', icon: ShieldCheck }, { page: 'holds', label: 'Legal holds', icon: LockKeyhole }, { page: 'exports', label: 'Audit exports', icon: ArrowDownToLine }, { page: 'value', label: 'Value report', icon: TrendingUp }] },
  { label: 'ADMINISTER', items: [{ page: 'builder', label: 'Institution Builder', icon: FlaskConical }, { page: 'intelligence', label: 'Intelligence Runtime', icon: Sparkles }, { page: 'state', label: 'Institutional state', icon: Network }, { page: 'integrations', label: 'Integrations', icon: Unplug }, { page: 'settings', label: 'Settings & Administration', icon: Settings2 }] },
] as const;
const pageTitles: Record<Page, [string, string]> = {
  overview: ['Operations Overview', 'Network posture, decision urgency, and the work that needs attention now.'],
  queue: ['Work Queue', 'A detailed view of disruption, commitments, and the decisions ahead.'],
  incident: ['', ''], reviews: ['Human reviews', 'Precisely scoped review. Explicit consequences. No operational execution.'],
  outcomes: ['Shadow & outcomes', 'Compare recommendations with operator decisions and observed effects.'],
  receipts: ['Receipt Inspector', 'Trace the evidence and versions behind each simulated decision.'],
  value: ['Value report', 'A measured view of the shadow pilot’s potential contribution.'],
  state: ['Institutional state', 'Inspect the relationships and evidence that inform the current decision.'],
  integrations: ['Integration health', 'Visibility into observation continuity and read-only connector scope.'],
  settings: ['Settings & Administration', 'Personal preferences are configured. Institutional power is governed.'],
  location: ['Location Overview', 'Local operational visibility within the authorized facility scope.'],
  actor: ['Actor Inspector', 'Structured operational records for an authorized agent or system.'],
  reconstructions: ['Reconstructions', 'Simulated forensic timelines, state replay, integrity and evidence relationships.'],
  exceptions: ['Execution exceptions', 'Unknown outcomes, missing acknowledgements and reconciliation work.'],
  integrity: ['Integrity status', 'Simulated hash-chain and signature verification for authoritative records.'],
  holds: ['Legal holds', 'Case-scoped retention and investigation controls.'],
  exports: ['Audit exports', 'Signed evidence package manifests and export history.'],
  builder: ['Institution Builder', 'Compile, validate and govern the institution before it reaches the runtime.'],
  intelligence: ['Intelligence Runtime', 'Inspect C1 releases, qualified capabilities, evaluations and deployment boundaries.'],
};
const scopes = [
  { id: 'institution', label: 'Meridian Logistics', detail: 'Institution · 4 networks' },
  { id: 'network', label: 'Mid-South Network', detail: 'Network · 3 facilities' },
  { id: 'facility', label: 'Memphis Fulfillment', detail: 'Facility · 12 systems · 8 active agents' },
  { id: 'workflow', label: 'Outbound Operations', detail: 'Workflow · 4 commitments at risk' },
] as const;
function routeFromHash(): { page: Page; incidentId: string } {
  const parts = window.location.hash.replace('#/', '').split('/');
  const incidentId = incidents.some(i => i.id === parts[1]) ? parts[1] : incidents[0].id;
  const page = parts[0] as Page;
  return { page: page in pageTitles ? page : 'overview', incidentId };
}
const baseActivity: Activity[] = [
  { id: 'a3', time: '10:42 CDT', title: 'Shadow recommendation recorded', detail: 'Three recovery plans compared. No action authorized or executed.', tone: 'teal' },
  { id: 'a2', time: '10:31 CDT', title: 'Capacity report admitted as reported evidence', detail: 'A supervisor report remains distinct from independent verification.', tone: 'blue' },
  { id: 'a1', time: '10:24 CDT', title: 'Disruption observation received', detail: 'Mock warehouse event linked to affected delivery commitments.', tone: 'amber' },
];
type Dialog = { kind: 'evidence'; evidence: Evidence } | { kind: 'review' } | { kind: 'recourse' } | { kind: 'receipt'; receipt: Receipt } | { kind: 'context' } | { kind: 'notifications' } | { kind: 'help' } | null;

export default function App() {
  const [route, setRoute] = useState(routeFromHash);
  const [scenario, setScenario] = useState<Scenario>('normal');
  const [role, setRole] = useState<Role>('Operator');
  const [scopeId, setScopeId] = useState<(typeof scopes)[number]['id']>('network');
  const [tab, setTab] = useState<WorkspaceTab>('decision');
  const [selectedPlans, setSelectedPlans] = useState<Record<string, string>>({});
  const [versions, setVersions] = useState<Record<string, number>>({});
  const [proposalVersions, setProposalVersions] = useState<Record<string, number>>({});
  const [capacityChanged, setCapacityChanged] = useState<Record<string, boolean>>({});
  const [reviews, setReviews] = useState<ReviewRecord[]>([]);
  const [receipts, setReceipts] = useState<Receipt[]>(initialReceipts);
  const [activities, setActivities] = useState<Record<string, Activity[]>>({});
  const [recourses, setRecourses] = useState<RecourseRecord[]>([]);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [toast, setToast] = useState('');
  const [acknowledged, setAcknowledged] = useState(false);
  const [askOpen, setAskOpen] = useState(false);
  const [commandOpen, setCommandOpen] = useState(false);
  const [commandQuery, setCommandQuery] = useState('');
  const [note, setNote] = useState(''); const [scopeAccepted, setScopeAccepted] = useState(false);
  const [recourseKind, setRecourseKind] = useState('Request additional evidence');
  const [liveState, setLiveState] = useState<'idle' | 'loading' | 'ready' | 'disconnected'>('idle');
  const sequence = useRef(842); const pending = useRef<ReturnType<typeof setTimeout> | null>(null);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const appMainRef = useRef<HTMLElement | null>(null);
  const fixtureIncident = incidents.find(i => i.id === route.incidentId)!;
  const incident = capacityChanged[fixtureIncident.id] ? { ...fixtureIncident, plans: fixtureIncident.plans.map((p, i) => i === 0 ? { ...p, cost: 31800, feasibility: 'Insufficient capacity', summary: 'Updated capacity is 260 units. This plan needs additional regional capacity and a budget escalation before it can proceed.', assumptions: ['Only 260 units of recovery capacity remain', 'Additional capacity and regional budget approval are required'] } : p) } : fixtureIncident;
  const plan = incident.plans.find(p => p.id === selectedPlans[incident.id]) ?? incident.plans[0];
  const version = versions[incident.id] ?? 142; const proposalVersion = proposalVersions[incident.id] ?? 3;
  const review = reviews.find(r => r.incidentId === incident.id);
  const incidentRecourses = recourses.filter(r => r.incidentId === incident.id);
  const blocked = ['stale', 'conflicted', 'restricted', 'disconnected', 'degraded', 'loading'].includes(scenario) || incidentRecourses.some(r => r.blocking && r.status === 'Open');
  const scope = scopes.find(item => item.id === scopeId) ?? scopes[1];

  useEffect(() => { const change = () => { setRoute(routeFromHash()); setTab('decision'); setSidebarOpen(false); }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  useEffect(() => () => { if (pending.current) clearTimeout(pending.current); if (toastTimer.current) clearTimeout(toastTimer.current); }, []);
  useEffect(() => { document.title = `${route.page === 'incident' ? incident.title : pageTitles[route.page][0]} · Cerebrum Prototype`; }, [route.page, incident.title]);
  useEffect(() => {
    if (!import.meta.env.VITE_CONTROL_PLANE_API_URL || route.incidentId !== 'INC-1042') { setLiveState('idle'); return; }
    const controller = new AbortController(); setLiveState('loading');
    controlPlaneClient.state('memphis-fulfillment', controller.signal).then(result => { setVersions(previous => ({ ...previous, [route.incidentId]: result.version })); setLiveState('ready'); }).catch(() => setLiveState('disconnected'));
    return () => controller.abort();
  }, [route.incidentId]);
  useEffect(() => { appMainRef.current?.scrollTo({ top: 0, behavior: 'auto' }); }, [route.page, route.incidentId]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(true); } if (event.key === 'Escape') setCommandOpen(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);

  function notify(message: string) { setToast(message); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''), 5500); }
  function navigate(page: Page, incidentId = incident.id) { window.location.hash = `/${page}/${incidentId}`; setRoute({ page, incidentId }); setTab('decision'); setSidebarOpen(false); }
  function log(title: string, detail: string, tone: Activity['tone'] = 'blue', id = incident.id) { setActivities(prev => ({ ...prev, [id]: [{ id: `event-${sequence.current++}`, time: '10:44 CDT · simulated session', title, detail, tone }, ...(prev[id] ?? baseActivity)] })); }
  function invalidate(id = incident.id) {
    if (pending.current) { clearTimeout(pending.current); pending.current = null; }
    setReviews(prev => prev.map(r => r.incidentId === id || r.status === 'pending' ? { ...r, status: 'invalidated' } : r));
    setReceipts(prev => prev.map(r => r.incidentId === id && r.type === 'Human shadow review' ? { ...r, status: 'Superseded' } : r));
  }
  function setMode(next: Scenario) {
    invalidate(); setScenario(next); setAcknowledged(false); setDialog(null);
    if (['stale', 'conflicted', 'disconnected', 'degraded'].includes(next)) log('Review invalidated by simulated condition', `Scenario changed to ${next}. Prior review cannot carry forward.`, 'amber');
    if (next === 'empty') navigate('queue');
    if (next === 'normal' && scenario !== 'normal') { setVersions(prev => ({ ...prev, [incident.id]: version + 1 })); notify('Mock snapshot resynchronized. Any previous review must be repeated.'); }
  }
  function choosePlan(next: Plan) { if (next.id === plan.id) return; invalidate(); setSelectedPlans(prev => ({ ...prev, [incident.id]: next.id })); setProposalVersions(prev => ({ ...prev, [incident.id]: proposalVersion + 1 })); log('Alternative plan selected', `${next.name}; proposal version advanced. No operational action taken.`); }
  function openReview() { setNote(''); setScopeAccepted(false); setDialog({ kind: 'review' }); }
  function openRecourse() { setNote(''); setRecourseKind('Request additional evidence'); setDialog({ kind: 'recourse' }); }
  function recordReceipt(title: string, type: string, detail: string, status: Receipt['status'] = 'Current') {
    const receipt: Receipt = { id: `SIM-RCP-${String(sequence.current++).padStart(4, '0')}`, incidentId: incident.id, title, type, plan: plan.name, stateVersion: version, proposalVersion, time: '10:44 CDT · simulated session', actor: `Jordan Ellis · ${role} demo persona`, status, detail, simulated: true };
    setReceipts(prev => [receipt, ...prev]); return receipt;
  }
  function submitReview() {
    if (blocked || role !== 'Approver' || !scopeAccepted || note.trim().length < 12 || plan.cost > 30000) return;
    const capturedNote = note.trim();
    setReviews(prev => [{ incidentId: incident.id, planId: plan.id, stateVersion: version, proposalVersion, status: 'pending' }, ...prev.filter(r => r.incidentId !== incident.id)]);
    setDialog(null); log('Human review submitted for simulated reevaluation', `${plan.name} · state v${version} · proposal v${proposalVersion}.`, 'amber');
    pending.current = setTimeout(() => {
      setReviews(prev => prev.map(r => r.incidentId === incident.id && r.status === 'pending' ? { ...r, status: 'reviewed' } : r));
      recordReceipt('Human scope review recorded', 'Human shadow review', `Simulated review of ${plan.name}. Reviewer rationale: ${capturedNote}. Mock Kernel disposition: SHADOW ONLY. No real approval, signature, reservation, or execution.`);
      log('Simulated Kernel reevaluation returned SHADOW ONLY', 'Human review retained as a simulated input. No execution authority issued.', 'teal');
      notify('Shadow review recorded. No action authorized or executed.'); pending.current = null;
    }, 850);
  }
  function submitRecourse() {
    if (role === 'Auditor' || scenario === 'disconnected' || note.trim().length < 12) return;
    const blocking = ['Correct an institutional fact', 'Challenge evidence', 'Mark an assumption invalid', 'Open an appeal', 'Report conflicting authority', 'Reject and return for replanning', 'Narrow proposal scope'].includes(recourseKind);
    const record: RecourseRecord = { id: `SIM-REQ-${sequence.current++}`, incidentId: incident.id, kind: recourseKind, detail: note.trim(), blocking, status: 'Open' };
    setRecourses(prev => [...prev, record]); if (blocking) invalidate();
    recordReceipt(recourseKind, 'Human recourse', `Simulated request: ${note.trim()}. Owner: ${incident.owner}. ${blocking ? 'Further review blocked; existing review invalidated.' : 'Additional review requested.'}`);
    log(recourseKind, `${note.trim()} · assigned to ${incident.owner}.`, 'amber');
    setDialog(null); setTab('activity'); notify('Simulated request recorded with an owner and receipt. History preserved.');
  }
  function resolveRecourse(id: string) { invalidate(); setRecourses(prev => prev.map(r => r.id === id ? { ...r, status: 'Resolved' } : r)); log('Simulated owner resolution recorded', `${id}. New human review is required. No past record was rewritten.`, 'teal'); recordReceipt('Owner resolution recorded', 'Recourse resolution', `${id} resolved in simulation. Original request preserved; fresh review required.`); notify('Owner resolution recorded. Review the proposal again.'); }
  function inspectCurrentReceipt() { const receipt = receipts.find(r => r.incidentId === incident.id); if (receipt) setDialog({ kind: 'receipt', receipt }); else notify('No receipt exists for this incident yet. Record a simulated review or recourse request.'); }
  function refreshState() { invalidate(); setCapacityChanged(prev => ({ ...prev, [incident.id]: true })); setVersions(prev => ({ ...prev, [incident.id]: version + 1 })); setProposalVersions(prev => ({ ...prev, [incident.id]: proposalVersion + 1 })); setSelectedPlans(prev => ({ ...prev, [incident.id]: incident.plans[1].id })); setScenario('normal'); log('Changed capacity reviewed; local alternative selected', 'Regional capacity is insufficient. A new local-recovery proposal replaces the prior selection.', 'amber'); notify('State refreshed; local recovery selected. A new scope review is required.'); }
  const safety = scenario === 'disconnected' ? ['Connection lost. Last snapshot retained.', 'Reviews are disabled until reconnection and resynchronization.'] : scenario === 'stale' ? ['Institutional state changed after this proposal was opened.', 'Review the changed consequences before continuing.'] : scenario === 'conflicted' ? ['Two capacity sources disagree.', 'Conflicting evidence blocks review. Reconcile the mock sources before continuing.'] : scenario === 'degraded' ? ['Reasoning service degraded.', 'Cached proposals remain visible; new review is paused in this simulation.'] : scenario === 'restricted' ? ['Demo compartment restriction active.', 'Only an access-denied fixture is displayed. No production authorization is implied.'] : null;

  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a>{sidebarOpen && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setSidebarOpen(false)} />}
    <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}><div className="brand"><span className="brand-mark"><Boxes size={27} strokeWidth={1.5} /></span><div>CEREBRUM</div><button className="icon-button mobile-only" aria-label="Close navigation" onClick={() => setSidebarOpen(false)}><PanelLeftClose size={20} /></button></div><button className="institution-switch" onClick={() => setDialog({ kind: 'context' })}><span className="institution-avatar">M</span><span><strong>Meridian Logistics</strong><small>Mid-South network</small></span><ChevronDown size={14} /></button><nav aria-label="Primary navigation">{navGroups.map(group => <div className="nav-group" key={group.label}><span className="nav-label">{group.label}</span>{group.items.map(item => <button key={item.page} className={`nav-item ${route.page === item.page || (route.page === 'incident' && item.page === 'queue') ? 'active' : ''}`} aria-current={route.page === item.page || (route.page === 'incident' && item.page === 'queue') ? 'page' : undefined} onClick={() => navigate(item.page)}><item.icon size={18} /><span>{item.label}</span>{'count' in item && <small>{item.count}</small>}</button>)}</div>)}</nav><div className="sidebar-bottom"><div className="pilot-card"><span><Radio size={14} /> SHADOW PILOT</span><strong>Observe. Evaluate. Learn.</strong><p>Operational execution is unavailable.</p><span className="pilot-progress"><i /></span><small>Phase 1 / 3 · frontend prototype</small></div><button className="help-button" onClick={() => setDialog({ kind: 'help' })}><CircleHelp size={17} /> Prototype guide <ArrowUpRight size={14} /></button><div className="profile"><div className="avatar">JE</div><div><strong>Jordan Ellis</strong><small>{role} persona · simulated</small></div></div></div></aside>
    <div className="app-body"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-only" aria-label="Open navigation" onClick={() => setSidebarOpen(true)}><Menu size={21} /></button><span className="breadcrumb-section">Operations</span><ChevronRight className="breadcrumb-chevron" size={14} /><label className="scope-selector"><span className="sr-only">Operational scope</span><select aria-label="Operational scope" value={scopeId} onChange={event => setScopeId(event.target.value as typeof scopeId)}>{scopes.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{scope.detail}</small></label><span className="operating-context"><Badge tone="blue" dot>Environment: SIMULATED</Badge><Badge tone="teal" dot>Workflow mode: SHADOW</Badge><Badge tone="neutral">Execution: DISABLED</Badge></span></div><div className="topbar-right"><button className="command-button" onClick={() => setCommandOpen(true)} aria-label="Open command palette">⌘K</button><button className="ask-topbar-button" onClick={() => setAskOpen(true)}><Sparkles size={14}/> Ask Cerebrum</button><span className={`sync-indicator ${scenario === 'disconnected' ? 'bad' : ''}`}><Signal size={15} />{scenario === 'disconnected' ? 'Disconnected · last trusted 10:31 CDT' : scenario === 'stale' ? 'State stale · update required' : 'State current · 10:44 CDT'}</span><button className="icon-button notification-button" onClick={() => setDialog({ kind: 'notifications' })} aria-label="View notifications"><Bell size={18} /><i /></button><button className="icon-button" onClick={() => setDialog({ kind: 'context' })} aria-label="View policy, versions and authority context"><Settings2 size={18} /></button></div></header>
    <div className="simulation-banner"><FlaskConical size={15} /><strong>SIMULATED ENVIRONMENT</strong><span>All data, identities, reviews, and Kernel behavior are mock. Workflow mode is shadow; execution is disabled.</span><span className="prototype-tag">PROTOTYPE 001</span></div>
    <div className="demo-toolbar prototype-controls" data-prototype-only="true"><div><span className="prototype-controls-label"><Settings2 size={13} /><strong>PROTOTYPE CONTROLS</strong><small>Demo-only toolbar · omitted from customer deployments</small></span><label>Scenario<select aria-label="Demo scenario" value={scenario} onChange={e => setMode(e.target.value as Scenario)}>{scenarios.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label>Persona<select aria-label="Demo persona" value={role} onChange={e => { invalidate(); setRole(e.target.value as Role); }}><option>Operator</option><option>Approver</option><option>Auditor</option></select></label></div><button className="text-link" onClick={() => { invalidate(); setScenario('normal'); setRole('Operator'); setReviews([]); setReceipts(initialReceipts); setRecourses([]); setActivities({}); setVersions({}); setProposalVersions({}); setSelectedPlans({}); setCapacityChanged({}); setDialog(null); setAcknowledged(false); navigate('overview', incidents[0].id); notify('Prototype reset to the original mock fixtures.'); }}><RotateCcw size={13} /> Reset prototype</button></div>
    <div className="safety-stack">{safety && <div className={`safety-rail ${scenario === 'disconnected' ? 'red' : ''}`} role="status"><TriangleAlert size={19} /><div><strong>{safety[0]}</strong><span>{safety[1]}</span></div><button onClick={() => setAcknowledged(true)} disabled={acknowledged}>{acknowledged ? 'Acknowledged · unresolved' : 'Acknowledge'}</button>{['conflicted', 'degraded', 'disconnected'].includes(scenario) && <button onClick={() => setMode('normal')}>{scenario === 'disconnected' ? 'Simulate reconnect' : 'Resolve mock condition'}</button>}</div>}
    {incidentRecourses.some(r => r.blocking && r.status === 'Open') && <div className="safety-rail"><MessageSquareText size={19} /><div><strong>Open recourse blocks further review.</strong><span>Existing review is invalidated. The assigned owner must resolve the request.</span></div><button onClick={() => { navigate('incident'); setTab('activity'); }}>View requests</button></div>}
    </div><main id="main-content" className="app-main" ref={appMainRef} tabIndex={-1}>
      {route.page === 'incident' ? <><div className="page-breadcrumb"><button onClick={() => navigate('queue')}><ArrowLeft size={13} /> Work Queue</button><span>/</span><span>{incident.id}</span></div><div className="page-heading incident-heading"><div><div className="heading-kicker"><span className="eyebrow">CEREBRUM WORKSPACE</span><Badge tone={incident.severity === 'Critical' ? 'red' : 'amber'} dot>{incident.severity}</Badge><Badge tone="amber">{review?.status === 'reviewed' ? 'Shadow reviewed' : 'Needs attention'}</Badge></div><h1>{incident.title}</h1><p>{incident.summary}</p><div className="incident-meta"><span><MapPin size={13} />{incident.site}</span><span>23 Sep 2026 · {incident.occurred} CDT</span><span>State v{version} · Proposal v{proposalVersion}</span></div></div><button className="button secondary receipt-shortcut" onClick={inspectCurrentReceipt}><FileCheck2 size={16} /> View receipt</button></div></> : <div className={`page-heading ${['reconstructions', 'exceptions', 'integrity', 'holds', 'builder'].includes(route.page) ? 'assurance-page-heading' : ''}`}><div className="heading-kicker"><span className="eyebrow">MERIDIAN LOGISTICS</span><Badge tone="teal">PHASE 1 · SIMULATED</Badge></div><h1>{pageTitles[route.page][0]}</h1><p>{pageTitles[route.page][1]}</p></div>}
      {scenario === 'loading' ? <><LoadingState /><button className="button secondary" onClick={() => setMode('normal')}>Complete simulated load</button></> : scenario === 'restricted' ? <Panel title="Restricted compartment"><EmptyState restricted title="This record is outside your simulated access scope" description="The denied-state fixture hides operational content. No restricted payload is present. Production access must be enforced on the server." action={<button className="button secondary" onClick={() => setMode('normal')}>Return to permitted mock records</button>} /></Panel> : <>
        {route.page === 'overview' && <OperationsOverview scenario={scenario} role={role} scope={scope} onOpen={id => navigate('incident', id)} onNavigate={navigate} onAsk={() => setAskOpen(true)} onNotify={notify} onLocation={() => navigate('location')} />}
        {route.page === 'queue' && <IncidentQueue onOpen={id => navigate('incident', id)} empty={scenario === 'empty'} />}
        {route.page === 'incident' && <>{liveState === 'disconnected' && <Notice title="Control Plane unavailable" tone="red">Live INC-1042 data could not be loaded. No fixture fallback is used for the configured API workflow.</Notice>}{liveState === 'loading' && <LoadingState />}{liveState === 'ready' && <Notice title="Live shadow workflow connected" tone="teal">Institutional state and lifecycle records are sourced from the authenticated Control Plane API. Execution remains disabled.</Notice>}<div className="metrics-grid"><Metric label="Commitments at risk" value={String(incident.commitments)} detail="Delivery windows before 16:00 CDT" tone="amber" /><Metric label="Orders affected" value={String(incident.orders)} detail="Across the selected workflow" /><Metric label="Modeled exposure" value={`$${Math.round(incident.exposure / 1000)}K`} detail={`Range $${Math.round(incident.exposure * .85 / 1000)}K–$${Math.round(incident.exposure * 1.15 / 1000)}K · not verified loss`} /><Metric label="Decision urgency" value={incident.timeRemaining} detail={`${incident.costOfDelay} delay cost · ${incident.nextRequiredAction}`} tone="teal" /></div><Workspace incident={incident} plan={plan} scenario={scenario} role={role} tab={tab} version={version} proposalVersion={proposalVersion} reviewStatus={review?.status ?? 'unreviewed'} blocked={blocked} activities={activities[incident.id] ?? baseActivity} recourses={incidentRecourses} onTab={setTab} onPlan={choosePlan} onEvidence={evidence => setDialog({ kind: 'evidence', evidence })} onReview={openReview} onRecourse={openRecourse} onReceipt={inspectCurrentReceipt} onRefresh={refreshState} onResolve={resolveRecourse} /></>}
        {route.page === 'reviews' && <ReviewsPage records={reviews} onOpen={id => navigate('incident', id)} />}
        {route.page === 'outcomes' && <><div className="report-toolbar"><label className="incident-picker">Historical incident<select aria-label="Outcome incident" value={incident.id} onChange={e => navigate('outcomes', e.target.value)}>{incidents.map(i => <option key={i.id} value={i.id}>{i.id} · {i.title}</option>)}</select></label><Badge>Historical fixtures · 23 Sep 2026</Badge></div><ShadowComparison incident={incident} plan={plan} /></>}
        {route.page === 'receipts' && <ReceiptList receipts={receipts} onInspect={receipt => setDialog({ kind: 'receipt', receipt })} />}
        {route.page === 'value' && <ValueReport />}
        {route.page === 'integrations' && <IntegrationsPage scenario={scenario} onScenario={setMode} />}
        {route.page === 'state' && <StatePage incident={incident} version={version} />}
        {route.page === 'settings' && <SettingsAdministration scenario={scenario} role={role} version={version} onNotify={notify} />}
        {route.page === 'location' && <LocationOverview onOpen={id => navigate('incident', id)} onActor={() => navigate('actor')} onNavigate={navigate} />}
        {route.page === 'actor' && <ActorInspector onLocation={() => navigate('location')} onOpen={id => navigate('incident', id)} />}
        {route.page === 'builder' && <InstitutionBuilder onNotify={notify} />}
        {route.page === 'intelligence' && <Panel title="Cerebrum C1 · c1-shadow-0.9.1" action={<Badge tone="teal">QUALIFIED SHADOW</Badge>}><Notice title="About this intelligence" tone="blue">C1 understands institutional situations, diagnoses changes, compares plans and proposes typed actions. It does not establish truth, grant authority or execute commands. The Kernel authorizes; Execution Assurance acts.</Notice><div className="two-columns"><Panel title="Qualified capabilities"><DefinitionList rows={[['Situation assessment', 'QUALIFIED_SHADOW · logistics.recovery'], ['Plan comparison', 'INTENDED · not production-qualified'], ['Typed action proposals', 'QUALIFIED_SHADOW · human review required'], ['Counterfactual supervision', 'RESEARCH_SUPPORTED · evaluation-bound']]}/></Panel><Panel title="Release boundary"><DefinitionList rows={[['Model hash', 'sha256:c1-shadow-demo'], ['ActionNet', 'actionnet-v0.4'], ['Operating modes', 'SHADOW only'], ['Approval authority', 'Institutional Kernel'], ['Unsupported', 'Unadmitted evidence · missing state version'], ['Fallback', 'ABSTAIN and request human review']]}/></Panel></div></Panel>}
        {route.page === 'reconstructions' && <ReconstructionPage onNotify={notify} />}
        {(['exceptions', 'integrity', 'holds', 'exports'] as Page[]).includes(route.page) && <AssuranceRegisterPage kind={route.page as 'exceptions' | 'integrity' | 'holds' | 'exports'} onNotify={notify} />}
      </>}
      <footer className="page-footer"><span><ShieldCheck size={13} /> Governed by design. Simulated in this prototype.</span><span>Meridian demo tenant · America/Chicago · UTC−05:00</span></footer>
    </main></div>
    {commandOpen && <div className="command-palette-backdrop" onMouseDown={() => setCommandOpen(false)}><section className="command-palette" role="dialog" aria-label="Command palette" onMouseDown={event => event.stopPropagation()}><div className="command-search"><Search size={16}/><input autoFocus value={commandQuery} onChange={event => setCommandQuery(event.target.value)} placeholder="Search facilities, commitments, agents, receipts..." /></div><div className="command-results">{[["Operations Overview","overview"],["Work Queue","queue"],["Human reviews","reviews"],["Reconstructions","reconstructions"],["Institution Builder","builder"],["Decision receipts","receipts"],["Settings & Administration","settings"]].filter(([label]) => label.toLowerCase().includes(commandQuery.toLowerCase())).map(([label, page]) => <button key={page} onClick={() => { navigate(page as Page); setCommandOpen(false); setCommandQuery(""); }}><span>{label}</span><small>Go to page</small></button>)}</div></section></div>}
    <AskCerebrum open={askOpen} onOpenChange={setAskOpen} incident={incident} plan={plan} page={route.page} version={version} scenario={scenario} activities={activities[incident.id] ?? baseActivity} receipt={receipts.find(receipt => receipt.incidentId === incident.id)} scope={scope} onShowEvidence={() => { navigate('incident', incident.id); setTab('evidence'); }} onComparePlans={() => { navigate('incident', incident.id); setTab('decision'); }} onReviewProposal={() => { navigate('incident', incident.id); setTab('decision'); setAskOpen(false); notify('Structured draft opened in the formal proposal workspace. It remains simulated and unauthorized.'); }} onOpenReceipt={inspectCurrentReceipt} onOpenReconstruction={() => { navigate('reconstructions', incident.id); setAskOpen(false); notify('Opened simulated forensic reconstruction.'); }} onNotify={notify} />
    {toast && <div className="toast" role="status"><Check size={17} /><span>{toast}</span><button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={16} /></button></div>}
    {dialog?.kind === 'receipt' && <Modal title="Receipt Inspector" onClose={() => setDialog(null)} wide><ReceiptDetails receipt={dialog.receipt} /></Modal>}
    {dialog?.kind === 'evidence' && <Modal title={dialog.evidence.title} onClose={() => setDialog(null)}><div className="modal-content"><Badge tone={dialog.evidence.status === 'Verified' ? 'teal' : 'amber'}>{dialog.evidence.status} · simulated</Badge><p>{dialog.evidence.description}</p><DefinitionList rows={[["Source / owner", `${dialog.evidence.source} / ${dialog.evidence.owner}`], ["Evidence identity", `${dialog.evidence.id} · ${dialog.evidence.version}`], ["Occurred / effective", `${incident.occurred} / ${incident.occurred} CDT`], ["Observed / recorded", `${dialog.evidence.time} / ${dialog.evidence.time} CDT`], ["Controller availability", `${dialog.evidence.time} CDT`], ["Reliability", dialog.evidence.status === 'Inferred' ? 'Uncalibrated illustrative estimate' : 'Fixture status; no source authentication'], ["Sensitivity", dialog.evidence.status === 'Restricted' ? 'Restricted — payload omitted' : 'Synthetic public data'], ["Permitted viewers", dialog.evidence.status === 'Restricted' ? 'Custodian only (not implemented)' : 'Demo personas'], ["Permitted models", dialog.evidence.status === 'Restricted' ? 'None' : 'No model is invoked'], ["Retention / export", 'Session memory; synthetic data only']]} />{dialog.evidence.status !== 'Restricted' && <button className="button secondary" disabled={role === 'Auditor' || scenario === 'disconnected'} onClick={() => { setNote(`Regarding ${dialog.evidence.id}: `); setRecourseKind('Challenge evidence'); setDialog({ kind: 'recourse' }); }}>Challenge this evidence</button>}</div></Modal>}
    {dialog?.kind === 'review' && <Modal title="Review exact proposal scope" onClose={() => setDialog(null)}><div className="modal-content"><Notice title="Simulated review — no real approval" tone="blue">This sends a mock human-review input for simulated Kernel reevaluation. It cannot reserve resources, dispatch work, or authorize execution.</Notice><DefinitionList rows={[["Proposal", `${plan.name} · v${proposalVersion}`], ["Requested scope", plan.resources], ["Estimated cost", money(plan.cost)], ["Affected commitments", `${plan.protected} of ${incident.commitments} modeled protected`], ["Authority / jurisdiction", 'MND-MEM-014 v2 · Tennessee · $30,000 ceiling'], ["Bound state / policy", `v${version} / POL-LOG-07 v2.4`], ["Consequences", 'Mock review only; unresolved assumptions remain'], ["Authentication", 'Demo persona only; no actual authentication']]} /><label className="field-label">Review rationale<textarea value={note} minLength={12} maxLength={1200} onChange={e => setNote(e.target.value)} placeholder="Explain why this precise scope is acceptable for shadow review…" /></label><label className="checkbox-label"><input type="checkbox" checked={scopeAccepted} onChange={e => setScopeAccepted(e.target.checked)} /><span>I reviewed the scope, cost, assumptions, and consequences. I understand this records a simulated shadow review only.</span></label><div className="dialog-actions"><button className="button secondary" onClick={() => setMode('stale')}>Simulate state change</button><button className="button primary" disabled={!scopeAccepted || note.trim().length < 12 || blocked || role !== 'Approver'} onClick={submitReview}>Submit scope review for simulated reevaluation</button></div><p className="micro">Rationale requires at least 12 characters. Real step-up authentication is outside this frontend prototype.</p></div></Modal>}
    {dialog?.kind === 'recourse' && <Modal title="Human review & recourse" onClose={() => setDialog(null)}><div className="modal-content"><p>Record a request against {incident.id}. The original evidence and decisions remain preserved.</p><label className="field-label">Request type<select aria-label="Request type" value={recourseKind} onChange={e => setRecourseKind(e.target.value)}>{['Request additional evidence', 'Correct an institutional fact', 'Challenge evidence', 'Mark an assumption invalid', 'Narrow proposal scope', 'Reject and return for replanning', 'Escalate to regional operations', 'Report conflicting authority', 'Open an appeal'].map(k => <option key={k}>{k}</option>)}</select></label><label className="field-label">Supporting evidence and requested resolution<textarea aria-label="Supporting evidence and requested resolution" value={note} onChange={e => setNote(e.target.value)} maxLength={1200} placeholder="Identify the disputed item, supporting evidence, and what should be reviewed…" /></label><DefinitionList rows={[["Resolution owner", incident.owner], ["Affected record", `${incident.id} · ${plan.name} · v${proposalVersion}`], ["History", 'Append-only simulated request'], ["Effect", ['Request additional evidence', 'Escalate to regional operations'].includes(recourseKind) ? 'Records a request; does not change state' : 'Blocks further review and invalidates existing review']]} /><button className="button primary full-width" disabled={note.trim().length < 12 || role === 'Auditor' || scenario === 'disconnected'} onClick={submitRecourse}>Record simulated request and receipt</button><p className="micro">At least 12 characters. Requests do not silently correct facts or broaden authority.</p></div></Modal>}
    {dialog?.kind === 'context' && <Modal title="Institution & operating context" onClose={() => setDialog(null)}><div className="modal-content"><Notice title="One synthetic tenant · no tenant switching" tone="blue">All identities, access scopes, and authority below are fixtures. No customer credentials are present.</Notice><DefinitionList rows={[["Institution / tenant", 'Meridian Logistics / meridian-demo'], ["Network / site", `Mid-South / ${incident.site}`], ["Environment", 'SIMULATED'], ["Workflow mode", 'SHADOW'], ["Execution", 'DISABLED'], ["Clock", '23 Sep 2026 · 10:44 CDT · America/Chicago'], ["State", `v${version} · ${scenario}`], ["Policy / IR", 'POL-LOG-07 v2.4 / IR v1.8'], ["Domain / runtime", 'logistics v0.3 / runtime 0.9.1 fixture'], ["Principal / role", `Jordan Ellis / ${role} persona`], ["Mandate / scope", 'MND-MEM-014 v2 / Tennessee / $30,000'], ["Connector health", scenario === 'disconnected' ? 'Disconnected fixture' : '2 read-only mock connectors'], ["Emergency intervention", 'Unavailable; no active execution exists']]} /></div></Modal>}
    {dialog?.kind === 'notifications' && <Modal title="Attention & escalations" onClose={() => setDialog(null)}><div className="modal-content"><Notice title="Decision window closes at 11:30 CDT">{incident.title} needs a scope review. Clock is a fixed historical replay.</Notice><Notice title="Carrier evidence remains outstanding">Transport desk owns the request for capacity confirmation.</Notice><button className="button secondary" onClick={() => { setDialog(null); navigate('reviews'); }}>Open human-review queue</button></div></Modal>}
    {dialog?.kind === 'help' && <Modal title="Explore the Phase 1 prototype" onClose={() => setDialog(null)}><div className="modal-content"><p>Use the scenario selector to explore loading, empty, stale, conflicted, restricted, degraded, and disconnected states.</p><ol className="guide-list"><li>Compare three plans in an incident workspace.</li><li>Inspect evidence and independent assurance dimensions.</li><li>Switch to the Approver demo persona and record a scope review.</li><li>Change state to invalidate the review, or challenge evidence.</li><li>Inspect the resulting simulated receipt and historical shadow comparison.</li></ol><Notice title="Nothing leaves this browser" tone="blue">There is no backend, model invocation, enterprise connection, real authentication, production execution, or credential storage. Changes live only in memory and reset on reload.</Notice></div></Modal>}
  </div>;
}
