import type { ActionProposal, ApiError, ApiResult, DecisionReceipt, KernelDecision, OutcomeRecord, RequestBinding } from '../../packages/contracts/src/index.js';

export type ControlPlaneState = { version: number; values: Record<string, unknown> };
export type Reconstruction = { incident_id: string; events: unknown[]; state: ControlPlaneState };
export type InstitutionSource = { tenant_id: string; institution_id: string; source_id: string; source_version: string; owner_id: string; provenance: string; sensitivity: string; effective_from: string; effective_to?: string; content_hash: string; classification_status: string; ingestion_timestamp: string; payload: Record<string, unknown> };
export type InstitutionCandidate = { tenant_id: string; institution_id: string; candidate_id: string; version: string; ir_hash: string; compiler_version: string; input_source_hashes: string[]; validation_findings: Array<Record<string, unknown>>; previous_candidate_id?: string; control_graph_diff: Record<string, unknown>; status: string; payload: Record<string, unknown>; created_at?: string };
export type InstitutionCompilationStatus = { institution_id: string; status: 'COMPILATION_REQUESTED' | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'RETRYING'; progress: { stage: string; percent: number }; candidate_id?: string; candidate?: InstitutionCandidate; error?: string };
export class ControlPlaneError extends Error { constructor(public readonly code: string, public readonly status: number, message: string) { super(message); } }
export class ControlPlaneClient {
  private readonly baseUrl = (import.meta.env.VITE_CONTROL_PLANE_API_URL as string | undefined)?.replace(/\/$/, '') ?? '';
  constructor(private readonly tokenProvider: () => string | undefined = () => (globalThis as { __CEREBRUM_TOKEN__?: string }).__CEREBRUM_TOKEN__) {}
  private async request<T>(path: string, init: RequestInit = {}, signal?: AbortSignal): Promise<T> {
    if (!this.baseUrl && !(globalThis as { __CEREBRUM_API_MOCK__?: boolean }).__CEREBRUM_API_MOCK__) throw new ControlPlaneError('API_UNCONFIGURED', 0, 'Control Plane API is not configured');
    const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 10_000); if (signal) signal.addEventListener('abort', () => controller.abort(), { once: true });
    try { const token = this.tokenProvider(); const headers = new Headers(init.headers); headers.set('accept', 'application/json'); if (token) headers.set('authorization', `Bearer ${token}`); const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers, signal: controller.signal }); const body = await response.json() as ApiResult<T> & ApiError; if (!response.ok) throw new ControlPlaneError(body.error?.code ?? 'API_ERROR', response.status, body.error?.message ?? 'Control Plane request failed'); return body.data; } finally { clearTimeout(timeout); }
  }
  state(scopeId: string, signal?: AbortSignal) { return this.request<ControlPlaneState>(`/v1/state/${encodeURIComponent(scopeId)}`, {}, signal); }
  incident(id: string, signal?: AbortSignal) { return this.request<Record<string, unknown>>(`/v1/incidents/${encodeURIComponent(id)}`, {}, signal); }
  proposal(id: string, signal?: AbortSignal) { return this.request<ActionProposal>(`/v1/proposals/${encodeURIComponent(id)}`, {}, signal); }
  decision(proposalId: string, signal?: AbortSignal) { return this.request<KernelDecision>(`/v1/decisions/${encodeURIComponent(proposalId)}`, {}, signal); }
  outcome(id: string, signal?: AbortSignal) { return this.request<OutcomeRecord>(`/v1/outcomes/${encodeURIComponent(id)}`, {}, signal); }
  receipt(id: string, signal?: AbortSignal) { return this.request<DecisionReceipt>(`/v1/receipts/${encodeURIComponent(id)}`, {}, signal); }
  reconstruction(id: string, signal?: AbortSignal) { return this.request<Reconstruction>(`/v1/reconstructions/${encodeURIComponent(id)}`, {}, signal); }
  private requestBinding(): RequestBinding { const id = typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; const identity = globalThis as { __CEREBRUM_TENANT_ID__?: string; __CEREBRUM_ACTOR_ID__?: string }; return { tenant_id: identity.__CEREBRUM_TENANT_ID__ ?? (import.meta.env.VITE_CONTROL_PLANE_TENANT_ID as string | undefined) ?? '', actor_id: identity.__CEREBRUM_ACTOR_ID__ ?? (import.meta.env.VITE_CONTROL_PLANE_ACTOR_ID as string | undefined) ?? '', correlation_id: `cc-${id}`, trace_id: `cc-${id}`, idempotency_key: `cc-${id}`, contract_version: '2026-09-24.v1', request_timestamp: new Date().toISOString() }; }
  sources(institutionId: string, signal?: AbortSignal) { return this.request<InstitutionSource[]>(`/v1/institutions/${encodeURIComponent(institutionId)}/sources`, {}, signal); }
  sourceVersions(institutionId: string, sourceId: string, signal?: AbortSignal) { return this.request<InstitutionSource[]>(`/v1/institutions/${encodeURIComponent(institutionId)}/sources/${encodeURIComponent(sourceId)}/versions`, {}, signal); }
  submitSource(institutionId: string, source: { source_id: string; source_version: string; provenance: string; sensitivity: string; effective_from: string; content_hash: string; classification_status?: string; payload?: Record<string, unknown> }, signal?: AbortSignal) { return this.request<InstitutionSource>(`/v1/institutions/${encodeURIComponent(institutionId)}/sources`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...source, binding: this.requestBinding() }) }, signal); }
  requestCompilation(institutionId: string, signal?: AbortSignal) { return this.request<{ institution_id: string; queued: boolean; status: string }>(`/v1/institution-compilations`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ institution_id: institutionId, binding: this.requestBinding() }) }, signal); }
  compilationStatus(institutionId: string, signal?: AbortSignal) { return this.request<InstitutionCompilationStatus>(`/v1/institution-compilations?institution_id=${encodeURIComponent(institutionId)}`, {}, signal); }
  candidate(institutionId: string, candidateId: string, signal?: AbortSignal) { return this.request<InstitutionCandidate>(`/v1/institution-compilations/${encodeURIComponent(candidateId)}?institution_id=${encodeURIComponent(institutionId)}`, {}, signal); }
}
export const controlPlaneClient = new ControlPlaneClient();
