import type { Evidence, Incident, Plan, Receipt, Scenario } from './types';

export const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
export const shortMoney = (n: number) => `$${(n / 1000).toFixed(1)}k`;
const memphisPlans: Plan[] = [
  { id: 'balanced', name: 'Regional rebalance', kind: 'Recommended', cost: 24600, recovery: '6–8 hours', protected: 4, risk: 'Low', feasibility: 'Conditional', summary: 'Transfer 320 orders to Nashville and reserve a limited Memphis overtime window.', actions: ['Request Nashville capacity confirmation for 320 orders', 'Propose 24 staff-hours of Memphis overtime', 'Stage revised routing for human review'], assumptions: ['Nashville retains 480 units of available capacity', 'Carrier capacity is confirmed before 12:00 CDT'], resources: '320 Nashville units · 24 staff-hours' },
  { id: 'local', name: 'Local recovery', kind: 'Lower cost', cost: 13100, recovery: '10–12 hours', protected: 2, risk: 'High', feasibility: 'Available', summary: 'Keep all orders in Memphis and extend the local recovery shift.', actions: ['Request a 48 staff-hour overtime window', 'Prioritize two time-critical customer commitments', 'Notify owners of two likely service delays'], assumptions: ['Local sortation recovers by 14:00 CDT', 'Two customer delivery windows can be renegotiated'], resources: '48 staff-hours · local sortation line B' },
  { id: 'transfer', name: 'Full network transfer', kind: 'Faster recovery', cost: 41800, recovery: '4–6 hours', protected: 4, risk: 'Medium', feasibility: 'Unconfirmed', summary: 'Transfer all affected volume across Nashville and Louisville with expedited transport.', actions: ['Request 640 units of regional capacity', 'Escalate the transport budget to regional operations', 'Obtain carrier confirmation for two expedited lanes'], assumptions: ['Both regional sites accept the additional volume', 'Regional approver grants an exception above $30,000'], resources: '640 regional units · 2 expedited carriers' },
];
function plansFor(prefix: string, costs: number[], counts: number[], actions: string[][]): Plan[] {
  return memphisPlans.map((p, i) => ({ ...p, id: `${prefix}-${p.id}`, cost: costs[i], protected: counts[i], name: ['Coordinated recovery', 'Local adjustment', 'Regional escalation'][i], summary: actions[i][0], actions: actions[i], assumptions: ['Site owner confirms current availability', 'Proposed change is reviewed within the decision window'], resources: ['1 recovery crew · reserve capacity', 'Local team · revised schedule', 'Regional team · expedited support'][i] }));
}
export const incidents: Incident[] = [
  { id: 'INC-1042', title: 'Memphis capacity disruption', site: 'Memphis fulfillment', severity: 'Critical', status: 'Review required', owner: 'Jordan Ellis', initials: 'JE', occurred: '10:18', observed: '10:24', exposure: 186400, orders: 640, commitments: 4, active: true, decisionDeadline: '11:07 CDT', timeRemaining: '23 min', costOfDelay: '$7.8K / hour', stateFreshness: '2 min ago', nextRequiredAction: 'Review proposal', summary: 'A sortation outage reduced outbound capacity by 38%. Four delivery commitments are at risk before the 16:00 carrier cutoff.', plans: memphisPlans, operatorAction: 'Extended local overtime; no regional transfer', actualRecovery: '10.2 hours', actualCost: 15800 },
  { id: 'INC-1041', title: 'Nashville carrier delay', site: 'Nashville distribution', severity: 'High', status: 'Evidence pending', owner: 'Maya Chen', initials: 'MC', occurred: '09:52', observed: '10:01', exposure: 68200, orders: 180, commitments: 2, active: true, decisionDeadline: '11:30 CDT', timeRemaining: '46 min', costOfDelay: '$2.1K / hour', stateFreshness: '6 min ago', nextRequiredAction: 'Obtain carrier evidence', summary: 'An inbound carrier is 95 minutes late. Two afternoon dispatch commitments depend on an updated arrival estimate.', plans: plansFor('nashville', [8200, 4100, 14600], [2, 1, 2], [['Request a backup carrier', 'Reserve a second loading window', 'Review the updated dispatch plan'], ['Reorder local loading slots', 'Notify one affected customer'], ['Escalate to regional transport', 'Request expedited cross-dock support']]), operatorAction: 'Reordered local loading slots', actualRecovery: '4.8 hours', actualCost: 4900 },
  { id: 'INC-1039', title: 'Louisville inventory variance', site: 'Louisville returns', severity: 'Moderate', status: 'In assessment', owner: 'Sam Rivera', initials: 'SR', occurred: '08:40', observed: '08:46', exposure: 32700, orders: 96, commitments: 1, active: true, decisionDeadline: '13:00 CDT', timeRemaining: '2h 16m', costOfDelay: '$900 / hour', stateFreshness: '4 min ago', nextRequiredAction: 'Reconcile inventory count', summary: 'A cycle-count variance affects 96 units. Reconciliation is required before committing replacement inventory.', plans: plansFor('louisville', [3400, 1600, 7900], [1, 0, 1], [['Request a targeted recount', 'Reserve replacement stock pending reconciliation'], ['Hold allocations until the evening count', 'Request a deadline extension'], ['Request regional replacement stock', 'Escalate disputed quantities to inventory control']]), operatorAction: 'Completed a targeted recount', actualRecovery: '3.1 hours', actualCost: 2800 },
  { id: 'INC-1036', title: 'Shift coverage recovered', site: 'Memphis fulfillment', severity: 'Moderate', status: 'Outcome recorded', owner: 'Jordan Ellis', initials: 'JE', occurred: '07:10', observed: '07:13', exposure: 21400, orders: 72, commitments: 1, active: false, decisionDeadline: 'Closed 09:12', timeRemaining: 'Resolved', costOfDelay: 'No longer accruing', stateFreshness: 'Outcome at 09:18', nextRequiredAction: 'Review shadow outcome', summary: 'The morning coverage gap was resolved by the operator. The historical shadow recommendation is ready for comparison.', plans: plansFor('coverage', [2200, 1200, 4600], [1, 1, 1], [['Request a qualified reserve team', 'Compare coverage against the shift commitment'], ['Reassign two qualified local staff', 'Confirm supervisor acceptance'], ['Request regional staffing support', 'Review travel and coverage costs']]), operatorAction: 'Reassigned two qualified local staff', actualRecovery: '1.4 hours', actualCost: 1200 },
];
export function evidenceFor(incident: Incident): Evidence[] {
  return [
    { id: 'EV-2081', title: 'Operational disruption report', status: 'Observed', source: 'Warehouse event feed', owner: 'Site operations', time: incident.observed, version: 'v3', description: incident.summary },
    { id: 'EV-2082', title: 'Committed delivery windows', status: 'Verified', source: 'Commitment ledger', owner: 'Customer operations', time: '10:27', version: 'v8', description: `${incident.commitments} commitment records matched against the mock ledger. Verification is simulated.` },
    { id: 'EV-2083', title: 'Available recovery capacity', status: 'Reported', source: 'Site supervisor report', owner: 'Regional operations', time: '10:31', version: 'v2', description: 'The site supervisor reports reserve capacity. A fresh independent confirmation is still required.' },
    { id: 'EV-2084', title: 'Recovery horizon estimate', status: 'Inferred', source: 'C1 planning fixture', owner: 'Planning team', time: '10:42', version: 'v1', description: 'Illustrative range derived from a mock planning scenario, not a calibrated forecast or a model invocation.' },
    { id: 'EV-2085', title: 'Carrier capacity confirmation', status: 'Missing', source: 'Carrier liaison', owner: 'Transport desk', time: '10:42', version: 'pending', description: 'No confirmation has been received in this scenario. The proposal remains conditional.' },
    { id: 'EV-2086', title: 'Capacity available through cutoff', status: 'Assumption', source: 'Plan assumption register', owner: 'Incident owner', time: '10:42', version: 'v1', description: 'Reserve capacity is assumed to remain available through the decision window. Challenge this assumption if new evidence disagrees.' },
    { id: 'EV-2087', title: 'Customer contract attachment', status: 'Restricted', source: 'Restricted compartment', owner: 'Contract custodian', time: '10:26', version: 'v4', description: 'Restricted content is not included in this frontend fixture.' },
  ];
}
export const scenarios: { value: Scenario; label: string }[] = [
  { value: 'normal', label: 'Live simulation' }, { value: 'loading', label: 'Loading' },
  { value: 'empty', label: 'Empty queue' }, { value: 'stale', label: 'Stale state' },
  { value: 'conflicted', label: 'Conflicting evidence' }, { value: 'restricted', label: 'Restricted access' },
  { value: 'degraded', label: 'Degraded service' }, { value: 'disconnected', label: 'Disconnected' },
];
export const initialReceipts: Receipt[] = [{ id: 'SIM-RCP-0841', incidentId: 'INC-1042', title: 'Initial shadow assessment', type: 'Shadow recommendation', plan: 'Regional rebalance', stateVersion: 142, proposalVersion: 3, time: '10:42 CDT', actor: 'C1 fixture · runtime 0.9.1', status: 'Current', detail: 'A simulated recommendation was recorded. No operational authorization, signature, or execution occurred.', simulated: true }];
