import { useState } from 'react';
import { ArrowDownRight, ArrowRight, Check, ChevronRight, Clock3, GitBranch, LockKeyhole, MessageSquareText, ShieldCheck, Sparkles, X } from 'lucide-react';
import { Badge, DefinitionList, Notice, Panel, TextLink } from './components';
import { evidenceFor, money, shortMoney } from './data';
import type { Activity, Evidence, Incident, Plan, RecourseRecord, ReviewStatus, Role, Scenario, WorkspaceTab } from './types';

interface WorkspaceProps {
  incident: Incident; plan: Plan; scenario: Scenario; role: Role; tab: WorkspaceTab;
  version: number; proposalVersion: number; reviewStatus: ReviewStatus; blocked: boolean;
  activities: Activity[]; recourses: RecourseRecord[];
  onTab: (tab: WorkspaceTab) => void; onPlan: (plan: Plan) => void;
  onEvidence: (evidence: Evidence) => void; onReview: () => void; onRecourse: () => void;
  onReceipt: () => void; onRefresh: () => void; onResolve: (id: string) => void;
}
export function AssuranceBreakdown({ scenario }: { scenario: Scenario }) {
  const rows = [
    { label: 'Evidence', value: scenario === 'conflicted' ? 'Conflicting' : '1 item missing', tone: 'amber', width: '70%' },
    { label: 'State freshness', value: scenario === 'stale' || scenario === 'disconnected' ? 'Needs refresh' : 'Current at 10:44', tone: scenario === 'stale' || scenario === 'disconnected' ? 'amber' : 'teal', width: '90%' },
    { label: 'Forecast', value: scenario === 'degraded' ? 'Unavailable' : 'Illustrative range', tone: 'blue', width: '50%' },
    { label: 'Policy', value: 'Review required', tone: 'amber', width: '75%' },
  ];
  return <Panel title="Assurance, dimension by dimension" action={<Badge>SIMULATED</Badge>}><div className="assurance-grid">{rows.map(row => <div key={row.label}><span>{row.label}</span><strong>{row.value}</strong><div className={`assurance-line ${row.tone}`} style={{ '--bar-width': row.width } as React.CSSProperties} /></div>)}</div><div className="assurance-foot"><span><ShieldCheck size={14} /> Envelope: shadow only</span><span>Feasibility: conditional</span><span>2 assumptions unresolved</span></div><p className="micro">Indicators show fixture status, not calibrated probabilities. Jurisdiction: Tennessee · local mandate only.</p></Panel>;
}
export function PlanComparison({ incident, plan, onPlan, disabled }: { incident: Incident; plan: Plan; onPlan: (p: Plan) => void; disabled: boolean }) {
  const [commitmentPlan, setCommitmentPlan] = useState<Plan | null>(null);
  const commitments = [
    { id: 'COM-1042-01', customer: 'Customer A', obligation: 'Customer A delivery', deadline: 'Today, 6 PM', value: '$42K', products: 'Priority retail order - 180 units', contract: 'Retail delivery SLA - Tier 1', evidence: 'EV-2082 v8', uncertainty: 'Carrier confirmation remains pending.' },
    { id: 'COM-1042-02', customer: 'Customer B', obligation: 'Customer B expedited shipment', deadline: 'Today, 9 PM', value: '$31K', products: 'Expedited clinical supplies - 96 units', contract: 'Expedited shipment SLA - Tier 1', evidence: 'EV-2082 v8', uncertainty: 'Expedited lane capacity is not independently confirmed.' },
    { id: 'COM-1042-03', customer: 'Retail replenishment', obligation: 'Retail replenishment order', deadline: 'Tomorrow, 7 AM', value: '$57K', products: 'Regional replenishment - 224 units', contract: 'Retail replenishment agreement', evidence: 'EV-2082 v8', uncertainty: 'Nashville reserve capacity is reported, not verified.' },
    { id: 'COM-1042-04', customer: 'Contracted carrier', obligation: 'Contracted carrier handoff', deadline: 'Tomorrow, 10 AM', value: '$38K', products: 'Carrier handoff - 140 units', contract: 'Carrier service commitment', evidence: 'EV-2085 pending', uncertainty: 'Carrier acknowledgement has not been received.' },
  ];
  const protectedCount = (index: number, selected: Plan) => index < selected.protected;
  return <Panel title="Three paths to recovery" eyebrow="ASSESSMENT & ALTERNATIVES" action={<Badge tone="blue"><Sparkles size={12} /> C1 fixture</Badge>}>
    <p className="panel-intro">Compare the operational trade-offs. Selecting a plan does not authorize an action.</p>
    <div className="table-scroll"><table className="plan-table"><thead><tr><th>Recovery plan</th><th>Protected commitments</th><th>Est. cost</th><th>Recovery</th><th>Risk</th></tr></thead><tbody>{incident.plans.map((p, index) => <tr key={p.id} className={p.id === plan.id ? 'selected' : ''}><td><label className="plan-choice"><input type="radio" name="recovery-plan" checked={p.id === plan.id} disabled={disabled} onChange={() => onPlan(p)} /><span><strong>{p.name}</strong><small>{index === 0 && <Sparkles size={11} />}{p.kind}</small></span></label></td><td><button className="commitment-count" type="button" onClick={() => setCommitmentPlan(p)} aria-label={`View ${p.protected} of ${incident.commitments} commitments for ${p.name}`}><strong>{p.protected}/{incident.commitments}</strong><small>{p.protected === incident.commitments ? 'protected' : 'protected - review at risk'}</small></button></td><td>{shortMoney(p.cost)}</td><td>{p.recovery}</td><td><Badge tone={p.risk === 'Low' ? 'teal' : p.risk === 'High' ? 'red' : 'amber'}>{p.risk}</Badge></td></tr>)}</tbody></table></div>
    <div className="selected-plan"><div className="selected-plan-top"><span className="eyebrow">SELECTED PLAN</span><span><GitBranch size={13} /> {plan.feasibility}</span></div><p>{plan.summary}</p><ol className="action-sequence">{plan.actions.map((action, index) => <li key={action}><span>{index + 1}</span>{action}</li>)}</ol><div className="plan-assumptions"><strong>Unresolved dependencies</strong>{plan.assumptions.map(a => <span key={a}><Clock3 size={13} />{a}</span>)}</div></div>
    {commitmentPlan && <section className="commitment-inspector" aria-label={`${commitmentPlan.name} commitment details`}><div className="commitment-inspector-heading"><div><span className="eyebrow">COMMITMENT LEDGER - SIMULATED</span><h3>{commitmentPlan.name}: affected commitments</h3><p>{commitmentPlan.protected}/{incident.commitments} commitments modeled protected by this plan.</p></div><button className="icon-button" type="button" aria-label="Close commitment details" onClick={() => setCommitmentPlan(null)}><X size={17} /></button></div><div className="commitment-table"><div className="commitment-table-head"><span>Commitment</span><span>Deadline</span><span>Value at risk</span><span>Plan result</span></div>{commitments.map((commitment, index) => { const isProtected = protectedCount(index, commitmentPlan); return <article key={commitment.id} className={isProtected ? 'protected' : 'at-risk'}><div><strong>{commitment.id}</strong><span>{commitment.obligation}</span><small>{commitment.customer} - {commitment.products}</small></div><span>{commitment.deadline}</span><span>{commitment.value}</span><Badge tone={isProtected ? 'teal' : 'amber'}>{isProtected ? 'Protected' : 'At risk'}</Badge><div className="commitment-detail"><span><strong>Contract / SLA</strong>{commitment.contract}</span><span><strong>Protection rationale</strong>{isProtected ? `Included in ${commitmentPlan.name.toLowerCase()} allocation.` : 'Capacity or carrier confirmation is insufficient.'}</span><span><strong>Evidence</strong>{commitment.evidence}</span><span><strong>Remaining uncertainty</strong>{commitment.uncertainty}</span></div></article>; })}</div></section>}    <div className="panel-foot"><ArrowDownRight size={14} /><span>Inaction exposure: <strong>{money(incident.exposure)}</strong> · scenario estimate, not expected loss</span></div>
  </Panel>;
}
export function EvidencePanel({ incident, scenario, onEvidence, compact = false }: { incident: Incident; scenario: Scenario; onEvidence: (e: Evidence) => void; compact?: boolean }) {
  const evidence = evidenceFor(incident).map(e => e.id === 'EV-2083' && scenario === 'conflicted' ? { ...e, status: 'Disputed' as const, description: 'Supervisor report: 480 units. Warehouse projection: 260 units. Reconciliation is required.' } : e.id === 'EV-2081' && scenario === 'stale' ? { ...e, status: 'Stale' as const } : e);
  return <Panel title={compact ? 'Evidence behind the recommendation' : 'Evidence & institutional state'} action={<span className="small-muted">{evidence.length} source records</span>}><div className="evidence-list">{(compact ? evidence.slice(0, 3) : evidence).map(e => <button className="evidence-row" key={e.id} onClick={() => onEvidence(e)}><span className={`evidence-icon ${e.status === 'Restricted' ? 'restricted-icon' : ''}`}>{e.status === 'Restricted' ? <LockKeyhole size={17} /> : e.status === 'Verified' ? <ShieldCheck size={17} /> : <FileGlyph />}</span><span className="evidence-main"><strong>{e.title}</strong><small>{e.source} · {e.version} · {e.time} CDT</small></span><Badge tone={e.status === 'Verified' ? 'teal' : ['Missing', 'Disputed', 'Stale', 'Assumption'].includes(e.status) ? 'amber' : 'neutral'}>{e.status}</Badge><ChevronRight size={14} /></button>)}</div>{!compact && <div className="panel-foot"><LockKeyhole size={14} /> Restricted attachment bytes are not shipped with this prototype.</div>}</Panel>;
}
function FileGlyph() { return <MessageSquareText size={17} />; }
export function ShadowComparison({ incident, plan }: { incident: Incident; plan: Plan }) {
  return <><Notice title="SHADOW RECOMMENDATION" tone="blue">Cerebrum did not execute this action. All observations, operator actions, and outcomes below are simulated historical fixtures.</Notice><Panel title="Recommendation vs. operator decision" eyebrow="HISTORICAL SHADOW REPLAY" action={<Badge tone="amber">Awaiting adjudication</Badge>}><div className="comparison-columns"><div><span className="eyebrow">CEREBRUM · 10:42 CDT</span><h3>{plan.name}</h3><p>{plan.summary}</p><DefinitionList rows={[["Predicted recovery", plan.recovery], ["Estimated cost", money(plan.cost)], ["Commitments modeled protected", `${plan.protected}/${incident.commitments}`], ["Information available", 'State v142 · EV-2081–2084'], ["Not available", 'Carrier confirmation']]} /></div><div><span className="eyebrow">ACTUAL OPERATOR · 10:57 CDT</span><h3>{incident.operatorAction}</h3><p>Mock operator record from the completed historical replay.</p><DefinitionList rows={[["Observed recovery", incident.actualRecovery], ["Recorded cost", money(incident.actualCost)], ["Decision-time information", 'Supervisor update at 10:51'], ["Operator rationale", 'Regional capacity unconfirmed'], ["Reviewer judgment", 'Pending independent review']]} /></div></div><div className="panel-foot">Different actions and information sets. The difference is not verified savings or evidence of causal benefit.</div></Panel><Panel title="Outcome comparison" action={<Badge>Recorded · not adjudicated</Badge>}><div className="outcome-grid"><div><span className="eyebrow">EXPECTED</span><h3>{plan.recovery}</h3><p>Scenario recovery estimate</p></div><ArrowRight size={22} /><div><span className="eyebrow">OBSERVED</span><h3>{incident.actualRecovery}</h3><p>Operator action · mock event log</p></div><div><span className="eyebrow">VERIFICATION</span><h3>Pending review</h3><p>Independent evidence reconciliation</p></div></div><DefinitionList rows={[["Verification policy", 'OUTCOME-LOGISTICS-01 · v1.2'], ["Verification evidence", 'Mock dispatch log + owner confirmation'], ["Downstream effects", 'One shift extended; staff impact unreviewed'], ["Displaced harm", 'Overtime burden requires review'], ["State update", 'Outcome recorded separately from verified outcome'], ["Verified Cerebrum savings", 'Not established']]} /></Panel></>;
}
export function AuthorityPanel({ incident, plan, role, scenario, reviewStatus, blocked, onReview, onRecourse, onReceipt, version, proposalVersion }: WorkspaceProps) {
  const overLimit = plan.cost > 30000;
  const decision = scenario === 'disconnected' ? 'UNAVAILABLE' : blocked ? 'ABSTAIN' : overLimit ? 'ESCALATION REQUIRED' : reviewStatus === 'reviewed' ? 'SHADOW ONLY' : 'REVIEW REQUIRED';
  return <aside className="authority-column"><Panel title="Authority & Kernel" eyebrow="INDEPENDENT DECISION BOUNDARY" className="authority-panel" action={<ShieldCheck size={20} />}><div className="kernel-result"><span className="eyebrow">SIMULATED KERNEL RESULT</span><strong>{decision}</strong><p>{blocked ? 'Review is blocked until the current condition is resolved.' : overLimit ? 'The proposed cost exceeds this local mandate.' : reviewStatus === 'reviewed' ? 'Human review recorded. Operational authorization remains absent.' : 'Human review and fresh capacity evidence are required.'}</p><code>{blocked ? 'STATE_OR_EVIDENCE_UNRESOLVED' : overLimit ? 'MANDATE_COST_LIMIT_EXCEEDED' : 'HUMAN_REVIEW_REQUIRED'}</code></div><DefinitionList rows={[["Review principal", `${role} · Jordan Ellis`], ["Mandate", 'MND-MEM-014 · v2'], ["Delegated by", 'Regional operations lead'], ["Jurisdiction", 'Tennessee · local operations'], ["Cost ceiling", '$30,000 · simulated'], ["Proposed cost", money(plan.cost)], ["Resource request", plan.resources], ["Reservation", 'Proposed · nothing reserved'], ["Decision window", 'Until 11:30 CDT · replay clock'], ["Bound versions", `State v${version} · proposal v${proposalVersion}`]]} /><div className="prohibited"><LockKeyhole size={14} /><div><strong>No execution authority</strong><p>Customer-system writes, credential issuance, dispatch, and real approvals are unavailable.</p></div></div><button className="button primary review-button" onClick={onReview} disabled={blocked || role !== 'Approver' || overLimit || reviewStatus === 'pending' || reviewStatus === 'reviewed'}>{reviewStatus === 'pending' ? 'Simulating Kernel reevaluation…' : reviewStatus === 'reviewed' ? <><Check size={16} /> Shadow review recorded</> : 'Review selected scope for simulated Kernel reevaluation'}</button>{role !== 'Approver' && <p className="micro">Switch the demo persona to Approver to explore this interaction. Persona selection is not authentication.</p>}<button className="button secondary full-width" onClick={onRecourse} disabled={role === 'Auditor' || scenario === 'disconnected'}><MessageSquareText size={15} /> Correct, challenge or escalate</button><TextLink onClick={onReceipt}>Inspect simulated receipt</TextLink><p className="micro">Frontend demonstration only. No server authorization or cryptographic approval is performed.</p></Panel><div className="owner-card"><div className="avatar">{incident.initials}</div><div><strong>{incident.owner}</strong><span>Incident owner · simulated</span></div><span className="online-dot" /></div></aside>;
}
export default function Workspace(props: WorkspaceProps) {
  const { incident, plan, scenario, tab, onTab, activities, recourses, onResolve } = props;
  return <><div className="workspace-tabs" role="tablist" aria-label="Incident workspace">{([['decision', 'Decision workspace'], ['evidence', 'Evidence & state'], ['shadow', 'Shadow & outcomes'], ['activity', 'Activity & recourse']] as const).map(([id, label], index, all) => <button id={`tab-${id}`} role="tab" tabIndex={tab === id ? 0 : -1} aria-controls="workspace-tab-content" aria-selected={tab === id} key={id} onClick={() => onTab(id)} onKeyDown={event => { const offset = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : 0; if (offset || event.key === 'Home' || event.key === 'End') { event.preventDefault(); const next = all[event.key === 'Home' ? 0 : event.key === 'End' ? all.length - 1 : (index + offset + all.length) % all.length][0]; onTab(next); document.getElementById(`tab-${next}`)?.focus(); } }}>{label}{id === 'evidence' && <span>7</span>}{id === 'activity' && recourses.length > 0 && <span>{recourses.length}</span>}</button>)}</div><div className="workspace-layout"><div className="workspace-main" id="workspace-tab-content" role="tabpanel" aria-labelledby={`tab-${tab}`}>
    {scenario === 'stale' && <Notice title="This proposal was opened against an older state"><div className="state-diff"><del>Available Nashville capacity: 480 units</del><ins>Available Nashville capacity: 260 units</ins><span>Regional rebalance requires 320 units. Review is disabled.</span></div><button className="button secondary" onClick={props.onRefresh}>Refresh state and review changed plans</button></Notice>}
    {tab === 'decision' && <><PlanComparison incident={incident} plan={plan} onPlan={props.onPlan} disabled={scenario === 'disconnected' || props.reviewStatus === 'pending'} /><AssuranceBreakdown scenario={scenario} /><EvidencePanel incident={incident} scenario={scenario} onEvidence={props.onEvidence} compact /></>}
    {tab === 'evidence' && <><EvidencePanel incident={incident} scenario={scenario} onEvidence={props.onEvidence} /><Panel title="Versioned state projection" action={<Badge>v{props.version}</Badge>}><DefinitionList rows={[["Institution", 'Meridian Logistics · tenant meridian-demo'], ["Site", incident.site], ["Occurred / effective", `${incident.occurred} CDT / ${incident.occurred} CDT`], ["Observed / recorded", `${incident.observed} CDT / ${incident.observed} CDT`], ["Controller availability", `${incident.observed} CDT · 23 Sep 2026`], ["Epistemic views", 'Observed · reported · inferred · authorized · committed'], ["Authorized / committed", 'No operational action authorized or committed'], ["Conflicts", scenario === 'conflicted' ? 'Two incompatible capacity reports' : 'No unresolved source conflict in this fixture']]} /></Panel></>}
    {tab === 'shadow' && <ShadowComparison incident={incident} plan={plan} />}
    {tab === 'activity' && <><Panel title="Human review & recourse" action={<Badge>{recourses.length} records</Badge>}>{recourses.length ? recourses.map(r => <div className="recourse-record" key={r.id}><div><Badge tone={r.status === 'Open' ? 'amber' : 'teal'}>{r.status}</Badge><strong>{r.kind}</strong><small>{r.id} · owner: {incident.owner}</small></div><p>{r.detail}</p><p className="micro">{r.blocking ? 'Blocks further review; previous review invalidated.' : 'Does not alter institutional state.'} Corrections remain requests until adjudicated.</p>{r.status === 'Open' && <button className="button secondary" disabled={props.role === 'Auditor' || scenario === 'disconnected'} onClick={() => onResolve(r.id)}>Simulate owner resolution; require new review</button>}</div>) : <p className="panel-intro">No challenges or appeals yet. Use “Correct, challenge or escalate” to create an auditable request.</p>}</Panel><Panel title="Decision timeline" action={<span className="small-muted">All events simulated</span>}><ol className="activity-list">{activities.map(a => <li key={a.id}><span className={`timeline-dot ${a.tone}`} /><div><small>{a.time}</small><strong>{a.title}</strong><p>{a.detail}</p></div></li>)}</ol></Panel></>}
  </div><AuthorityPanel {...props} /></div></>;
}
