import { createHash } from 'node:crypto';
export type SignatureEnvelope = { signature: string; key_id: string; key_version?: string; algorithm: string; signed_at: string; digest: string };
export interface ReceiptSigner { sign(payload: string): Promise<SignatureEnvelope>; verify(payload: string, signature: string, key_id: string, key_version?: string): Promise<boolean>; }
export interface KmsProvider { signDigest(digest: string, keyId: string): Promise<{ signature: string; key_id: string; key_version?: string; algorithm: string }>; verifyDigest(digest: string, signature: string, keyId: string, keyVersion?: string): Promise<boolean>; }
export const canonicalize = (value: unknown): string => { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`; return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalize(item)}`).join(',')}}`; };
export const digestReceipt = (value: unknown) => `sha256:${createHash('sha256').update(canonicalize(value)).digest('hex')}`;
export class KmsReceiptCustody implements ReceiptSigner { constructor(private readonly provider: KmsProvider, private readonly keyId: string) { if (!keyId) throw new Error('KMS_KEY_ID is required'); } async sign(payload: string): Promise<SignatureEnvelope> { const digest = `sha256:${createHash('sha256').update(payload).digest('hex')}`; const result = await this.provider.signDigest(digest, this.keyId); return { ...result, digest, signed_at: new Date().toISOString() }; } verify(payload: string, signature: string, keyId: string, keyVersion?: string) { const digest = `sha256:${createHash('sha256').update(payload).digest('hex')}`; return this.provider.verifyDigest(digest, signature, keyId, keyVersion); } }
export class LocalReceiptSigner implements ReceiptSigner { constructor(private readonly keyId = 'local-test-key-v1') {} async sign(payload: string): Promise<SignatureEnvelope> { const digest = `sha256:${createHash('sha256').update(payload).digest('hex')}`; return { signature: `local:${this.keyId}:${digest}`, key_id: this.keyId, key_version: '1', algorithm: 'TEST-HASH', signed_at: new Date(0).toISOString(), digest }; } async verify(payload: string, signature: string, keyId: string) { const digest = `sha256:${createHash('sha256').update(payload).digest('hex')}`; return keyId === this.keyId && signature === `local:${this.keyId}:${digest}`; } }
export class DeterministicKmsProvider implements KmsProvider { constructor(private readonly versions = new Map<string, string>([['kms-test-key', 'v1']])) {} async signDigest(digest: string, keyId: string) { const version = this.versions.get(keyId); if (!version) throw new Error('KMS_KEY_UNAVAILABLE'); return { signature: `kms:${keyId}:${version}:${digest}`, key_id: keyId, key_version: version, algorithm: 'KMS-SHA256-RSA-PSS' }; } async verifyDigest(digest: string, signature: string, keyId: string, keyVersion?: string) { return signature === `kms:${keyId}:${keyVersion ?? this.versions.get(keyId)}:${digest}`; } }
export class UnavailableKmsProvider implements KmsProvider { async signDigest(_digest: string, _keyId: string): Promise<{ signature: string; key_id: string; key_version?: string; algorithm: string }> { throw new Error('KMS_UNAVAILABLE'); } async verifyDigest(_digest: string, _signature: string, _keyId: string, _keyVersion?: string): Promise<boolean> { throw new Error('KMS_UNAVAILABLE'); } }
/** AWS KMS adapter. The SDK is loaded by the server process; private key material never enters this module. */
export class AwsKmsProvider implements KmsProvider {
  private readonly clientPromise: Promise<any>;
  constructor(private readonly region = (globalThis as any).process?.env?.AWS_REGION ?? 'us-east-1') { const load = new Function('s', 'return import(s)') as (specifier: string) => Promise<any>; this.clientPromise = load('@aws-sdk/client-kms').then((sdk: any) => new sdk.KMSClient({ region: this.region })); }
  private bytes(digest: string) { const hex = digest.replace(/^sha256:/, ''); return new Uint8Array(hex.match(/.{1,2}/g)?.map(pair => Number.parseInt(pair, 16)) ?? []); }
  async signDigest(digest: string, keyId: string) { const sdk: any = await (new Function('s', 'return import(s)') as (specifier: string) => Promise<any>)('@aws-sdk/client-kms'); const client = await this.clientPromise; const result = await client.send(new sdk.SignCommand({ KeyId: keyId, Message: this.bytes(digest), MessageType: 'DIGEST', SigningAlgorithm: 'RSASSA_PSS_SHA_256' })); if (!result.Signature) throw new Error('KMS_SIGNATURE_MISSING'); const encoded = (globalThis as any).Buffer.from(result.Signature).toString('base64'); return { signature: encoded, key_id: String(result.KeyId ?? keyId), key_version: String(result.KeyId ?? keyId), algorithm: 'RSASSA_PSS_SHA_256' }; }
  async verifyDigest(digest: string, signature: string, keyId: string) { const sdk: any = await (new Function('s', 'return import(s)') as (specifier: string) => Promise<any>)('@aws-sdk/client-kms'); const client = await this.clientPromise; const result = await client.send(new sdk.VerifyCommand({ KeyId: keyId, Message: this.bytes(digest), MessageType: 'DIGEST', Signature: (globalThis as any).Buffer.from(signature, 'base64'), SigningAlgorithm: 'RSASSA_PSS_SHA_256' })); return result.SignatureValid === true; }
}


