import type { BreakGlassGrant, DecisionReceipt, EventEnvelope, EvidenceRecord, OutcomeRecord, ActionProposal, KernelDecision, ExecutionCommand, ExecutionStatus } from '../../contracts/src/index.js';

export type StoredIncident = { incident_id: string; tenant_id: string; scope_id: string; state_version: number; status: string; values?: Record<string, unknown>; state_hash?: string };
export type StateDiff = { tenant_id: string; scope_id: string; version: number; diff: Record<string, unknown>; state_hash: string };
export type EvidenceRelationship = { tenant_id: string; relationship_id: string; event_id: string; evidence_id: string; relationship_type: 'ADMITTED_FOR' | 'RESTRICTED_FROM' | 'DISPUTED_BY' | 'REJECTED_FOR' };
export type StoredReview = { review_id: string; proposal_id: string; actor_id: string; approved: boolean; recorded_at: string; proposal_hash?: string; context_hash?: string };
export type StoredShadow = { proposal_id: string; recorded_at: string; executed: false; credentials: 'NONE' };
export type StoredKernelDecision = KernelDecision & { tenant_id: string; recorded_at?: string };
export type OutboxMessage = { outbox_id: string; tenant_id: string; dedupe_key: string; topic: string; aggregate_id: string; payload: Record<string, unknown>; correlation_id: string; trace_id: string; state_version?: number; status?: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'DEAD_LETTER'; attempts?: number; available_at?: string; lease_expires_at?: string; worker_id?: string; last_error?: string; last_error_code?: string; last_error_metadata?: Record<string, unknown> };
export type ReceiptCustodyRecord = { tenant_id: string; receipt_id: string; status: 'SIGNED' | 'SIGNATURE_FAILED'; digest: string; signature: string; algorithm: string; key_id: string; key_version?: string; signed_at: string };
export type ExecutionTransition = { transition_id: string; tenant_id: string; command_id: string; from_status: ExecutionStatus | null; to_status: ExecutionStatus; payload: Record<string, unknown>; recorded_at: string; };
export type InstitutionSourceRecord = { tenant_id: string; institution_id: string; source_id: string; source_version: string; owner_id: string; provenance: string; sensitivity: string; effective_from: string; effective_to?: string; content_hash: string; classification_status: string; ingestion_timestamp: string; payload: Record<string, unknown>; };
export type InstitutionCandidateRecord = { tenant_id: string; institution_id: string; candidate_id: string; version: string; ir_hash: string; compiler_version: string; input_source_hashes: string[]; validation_findings: Array<Record<string, unknown>>; previous_candidate_id?: string; control_graph_diff: Record<string, unknown>; status: string; payload: Record<string, unknown>; created_at?: string; };
export type InstitutionReleaseRecord = { tenant_id: string; institution_id: string; release_id: string; candidate_id: string; version: number; lifecycle_state: string; manifest_hash: string; signature_status: string; correlation_id?: string; trace_id?: string; payload: Record<string, unknown>; };

export interface PlatformRepositories {
  transaction<T>(tenantId: string, work: (repositories: PlatformRepositories) => Promise<T>): Promise<T>;
  lockScope(scopeId: string): Promise<void>;
  appendEvent(event: EventEnvelope): Promise<boolean>;
  getEvents(tenantId: string, incidentId?: string): Promise<EventEnvelope[]>;
  putEvidence(record: EvidenceRecord & { tenant_id: string }): Promise<void>;
  getState(tenantId: string, scopeId: string): Promise<{ version: number; values: Record<string, unknown> } | null>;
  putState(incident: StoredIncident, expectedVersion: number): Promise<boolean>;
  putStateDiff(diff: StateDiff): Promise<void>;
  linkEvidence(relationship: EvidenceRelationship): Promise<void>;
  putIncident(incident: StoredIncident): Promise<void>;
  putProposal(proposal: ActionProposal & { tenant_id: string }): Promise<void>;
  getProposal(tenantId: string, proposalId: string): Promise<(ActionProposal & { tenant_id: string }) | null>;
  putReview(review: StoredReview & { tenant_id: string }): Promise<void>;
  getReview(tenantId: string, proposalId: string): Promise<(StoredReview & { tenant_id: string }) | null>;
  putKernelDecision(decision: StoredKernelDecision): Promise<void>;
  getKernelDecision(tenantId: string, proposalId: string): Promise<StoredKernelDecision | null>;
  putMandate(mandate: Record<string, unknown> & { tenant_id: string }): Promise<void>;
  putShadow(shadow: StoredShadow & { tenant_id: string }): Promise<void>;
  putOutcome(outcome: OutcomeRecord & { tenant_id: string }): Promise<void>;
  getOutcome(tenantId: string, outcomeId: string): Promise<(OutcomeRecord & { tenant_id: string }) | null>;
  putReceipt(receipt: DecisionReceipt & { tenant_id: string }): Promise<void>;
  getReceipt(tenantId: string, receiptId: string): Promise<(DecisionReceipt & { tenant_id: string }) | null>;
  listReceipts(tenantId: string, incidentId?: string): Promise<Array<DecisionReceipt & { tenant_id: string }>>;
  putReceiptCustody(record: ReceiptCustodyRecord): Promise<boolean>;
  getReceiptCustody(tenantId: string, receiptId: string): Promise<ReceiptCustodyRecord | null>;
  claimReceiptSigning(tenantId: string, receiptId: string, workerId: string, leaseMs?: number): Promise<boolean>;
  completeReceiptSigning(tenantId: string, receiptId: string): Promise<void>;
  putBreakGlass(grant: BreakGlassGrant): Promise<void>;
  getBreakGlass(tenantId: string, grantId: string): Promise<BreakGlassGrant | null>;
  updateBreakGlass(grant: BreakGlassGrant): Promise<boolean>;
  getIdempotency(tenantId: string, key: string): Promise<unknown | undefined>;
  claimIdempotency(tenantId: string, key: string, response: unknown): Promise<{ claimed: boolean; response: unknown }>;
  putIdempotencyResponse(tenantId: string, key: string, response: unknown): Promise<void>;
  enqueueOutbox(message: OutboxMessage): Promise<boolean>;
  claimOutbox(tenantId: string, workerId: string, leaseMs?: number): Promise<OutboxMessage | null>;
  completeOutbox(tenantId: string, outboxId: string): Promise<void>;
  retryOutbox(tenantId: string, outboxId: string, error: string, maxAttempts?: number, delayMs?: number): Promise<'RETRYING' | 'DEAD_LETTER'>;
  getOutboxMetrics(tenantId: string): Promise<{ pending: number; processing: number; completed: number; dead_letter: number; oldest_age_ms: number | null; retries: number }>;
  requeueOutbox(tenantId: string, outboxId: string): Promise<boolean>;
  getActorMembership(tenantId: string, actorId: string, role: string): Promise<{ active: boolean; facility_scope: string | null; mandate_expires_at: string | null; financial_limit: number | null } | null>;
  putExecution(command: ExecutionCommand): Promise<boolean>;
  getExecution(tenantId: string, commandId: string): Promise<(ExecutionCommand & { tenant_id: string }) | null>;
  updateExecution(command: ExecutionCommand & { tenant_id: string }, expectedStatus: ExecutionStatus): Promise<boolean>;
  putExecutionTransition(transition: ExecutionTransition): Promise<boolean>;
  listExecutionTransitions(tenantId: string, commandId: string): Promise<ExecutionTransition[]>;
  listExecutions(tenantId: string, incidentId?: string): Promise<Array<ExecutionCommand & { tenant_id: string }>>;
  putInstitutionSource(source: InstitutionSourceRecord): Promise<boolean>;
  listInstitutionSources(tenantId: string, institutionId: string): Promise<InstitutionSourceRecord[]>;
  listInstitutionSourceVersions(tenantId: string, institutionId: string, sourceId: string): Promise<InstitutionSourceRecord[]>;
  createInstitutionCandidate(candidate: InstitutionCandidateRecord): Promise<boolean>;
  getInstitutionCandidate(tenantId: string, institutionId: string, candidateId: string): Promise<InstitutionCandidateRecord | null>;
  createInstitutionRelease(release: InstitutionReleaseRecord): Promise<boolean>;
  getInstitutionRelease(tenantId: string, releaseId: string): Promise<InstitutionReleaseRecord | null>;
  transitionInstitutionRelease(tenantId: string, releaseId: string, expectedState: string, expectedVersion: number, nextState: string, correlationId: string, traceId: string, payload: Record<string, unknown>): Promise<boolean>;
}

export class InMemoryPlatformRepositories implements PlatformRepositories {
  private events: EventEnvelope[] = []; private states = new Map<string, { version: number; values: Record<string, unknown> }>(); private receipts = new Map<string, DecisionReceipt & { tenant_id: string }>(); private proposals = new Map<string, ActionProposal & { tenant_id: string }>(); private decisions = new Map<string, StoredKernelDecision>(); private reviews = new Map<string, StoredReview & { tenant_id: string }>(); private outcomes = new Map<string, OutcomeRecord & { tenant_id: string }>(); private idempotency = new Map<string, unknown>();
  async transaction<T>(_tenantId: string, work: (repositories: PlatformRepositories) => Promise<T>): Promise<T> { return work(this); }
  async lockScope(_scopeId: string) {}
  async appendEvent(event: EventEnvelope) { if (this.events.some(existing => existing.tenant_id === event.tenant_id && existing.event_id === event.event_id)) return false; this.events.push(structuredClone(event)); return true; }
  async getEvents(tenantId: string, incidentId?: string): Promise<EventEnvelope[]> { return this.events.filter(event => event.tenant_id === tenantId && (!incidentId || event.incident_id === incidentId)).map(event => structuredClone(event)); }
  async putEvidence() {}
  async getState(_tenantId: string, _scopeId: string) { return null; }
  async putState(incident: StoredIncident, expectedVersion: number) { if (incident.state_version !== expectedVersion && incident.state_version !== expectedVersion + 1) return false; this.states.set(`${incident.tenant_id}:${incident.scope_id}`, { version: incident.state_version, values: structuredClone(incident.values ?? {}) }); return true; }
  async putStateDiff() {}
  async linkEvidence() {}
  async putIncident() {}
  async putProposal(proposal: ActionProposal & { tenant_id: string }) { const key = `${proposal.tenant_id}:${proposal.proposal_id}`; if (!this.proposals.has(key)) this.proposals.set(key, structuredClone(proposal)); }
  async getProposal(tenantId: string, proposalId: string) { return this.proposals.get(`${tenantId}:${proposalId}`) ?? null; }
  async putReview(review: StoredReview & { tenant_id: string }) { this.reviews.set(`${review.tenant_id}:${review.proposal_id}`, structuredClone(review)); }
  async getReview(tenantId: string, proposalId: string) { return this.reviews.get(`${tenantId}:${proposalId}`) ?? null; }
  async putKernelDecision(decision: StoredKernelDecision) { this.decisions.set(`${decision.tenant_id}:${decision.proposal_id}`, structuredClone(decision)); }
  async getKernelDecision(tenantId: string, proposalId: string) { return this.decisions.get(`${tenantId}:${proposalId}`) ?? null; }
  async putMandate() {}
  async putShadow() {}
  async putOutcome(outcome: OutcomeRecord & { tenant_id: string }) { this.outcomes.set(`${outcome.tenant_id}:${outcome.outcome_id}`, structuredClone(outcome)); }
  async getOutcome(tenantId: string, outcomeId: string) { return this.outcomes.get(`${tenantId}:${outcomeId}`) ?? null; }
  async putReceipt(receipt: DecisionReceipt & { tenant_id: string }) { this.receipts.set(`${receipt.tenant_id}:${receipt.receipt_id}`, structuredClone(receipt)); }
  async getReceipt(tenantId: string, receiptId: string) { return this.receipts.get(`${tenantId}:${receiptId}`) ?? null; }
  async listReceipts(tenantId: string, incidentId?: string) { return [...this.receipts.values()].filter(receipt => receipt.tenant_id === tenantId && (!incidentId || receipt.incident_id === incidentId)).map(receipt => structuredClone(receipt)); }
  private custody = new Map<string, ReceiptCustodyRecord>();
  async putReceiptCustody(record: ReceiptCustodyRecord) { const key = `${record.tenant_id}:${record.receipt_id}`; if (this.custody.has(key)) return false; this.custody.set(key, structuredClone(record)); return true; }
  async getReceiptCustody(tenantId: string, receiptId: string) { return this.custody.get(`${tenantId}:${receiptId}`) ?? null; }
  private signingClaims = new Map<string, { worker_id: string; expires: number; complete: boolean }>();
  async claimReceiptSigning(tenantId: string, receiptId: string, workerId: string, leaseMs = 30000) { const key = `${tenantId}:${receiptId}`; const existing = this.signingClaims.get(key); if (existing?.complete || (existing && existing.expires > Date.now())) return false; this.signingClaims.set(key, { worker_id: workerId, expires: Date.now() + leaseMs, complete: false }); return true; }
  async completeReceiptSigning(tenantId: string, receiptId: string) { const claim = this.signingClaims.get(`${tenantId}:${receiptId}`); if (claim) claim.complete = true; }
  private executions = new Map<string, ExecutionCommand & { tenant_id: string }>(); private executionTransitions = new Map<string, ExecutionTransition>();
  async putExecution(command: ExecutionCommand) { const key = `${command.tenant_id}:${command.command_id}`; if (this.executions.has(key)) return false; this.executions.set(key, structuredClone(command as ExecutionCommand & { tenant_id: string })); return true; }
  async getExecution(tenantId: string, commandId: string) { return this.executions.get(`${tenantId}:${commandId}`) ?? null; }
  async updateExecution(command: ExecutionCommand & { tenant_id: string }, expectedStatus: ExecutionStatus) { const key = `${command.tenant_id}:${command.command_id}`; const current = this.executions.get(key); if (!current || current.status !== expectedStatus) return false; this.executions.set(key, structuredClone(command)); return true; }
  async putExecutionTransition(transition: ExecutionTransition) { if (this.executionTransitions.has(`${transition.tenant_id}:${transition.transition_id}`)) return false; this.executionTransitions.set(`${transition.tenant_id}:${transition.transition_id}`, structuredClone(transition)); return true; }
  async listExecutionTransitions(tenantId: string, commandId: string) { return [...this.executionTransitions.values()].filter(item => item.tenant_id === tenantId && item.command_id === commandId).map(item => structuredClone(item)); }
  async listExecutions(tenantId: string, incidentId?: string) { return [...this.executions.values()].filter(item => item.tenant_id === tenantId && (!incidentId || item.incident_id === incidentId)).map(item => structuredClone(item)); }
  private institutionSources = new Map<string, InstitutionSourceRecord>();
  async putInstitutionSource(source: InstitutionSourceRecord) { const key = `${source.tenant_id}:${source.institution_id}:${source.source_id}:${source.source_version}`; if (this.institutionSources.has(key)) return false; this.institutionSources.set(key, structuredClone(source)); return true; }
  async listInstitutionSources(tenantId: string, institutionId: string) { return [...this.institutionSources.values()].filter(item => item.tenant_id === tenantId && item.institution_id === institutionId).map(item => structuredClone(item)); }
  async listInstitutionSourceVersions(tenantId: string, institutionId: string, sourceId: string) { return [...this.institutionSources.values()].filter(item => item.tenant_id === tenantId && item.institution_id === institutionId && item.source_id === sourceId).sort((a, b) => a.source_version.localeCompare(b.source_version)).map(item => structuredClone(item)); }
  private institutionCandidates = new Map<string, InstitutionCandidateRecord>();
  async createInstitutionCandidate(candidate: InstitutionCandidateRecord) { const key = `${candidate.tenant_id}:${candidate.institution_id}:${candidate.candidate_id}`; if (this.institutionCandidates.has(key)) return false; this.institutionCandidates.set(key, structuredClone(candidate)); return true; }
  async getInstitutionCandidate(tenantId: string, institutionId: string, candidateId: string) { return structuredClone(this.institutionCandidates.get(`${tenantId}:${institutionId}:${candidateId}`) ?? null); }
  private institutionReleases = new Map<string, InstitutionReleaseRecord>();
  async createInstitutionRelease(release: InstitutionReleaseRecord) { const key = `${release.tenant_id}:${release.release_id}`; if (this.institutionReleases.has(key)) return false; this.institutionReleases.set(key, structuredClone(release)); return true; }
  async getInstitutionRelease(tenantId: string, releaseId: string) { return structuredClone(this.institutionReleases.get(`${tenantId}:${releaseId}`) ?? null); }
  async transitionInstitutionRelease(tenantId: string, releaseId: string, expectedState: string, expectedVersion: number, nextState: string, correlationId: string, traceId: string, _payload: Record<string, unknown>) { const key = `${tenantId}:${releaseId}`; const current = this.institutionReleases.get(key); if (!current || current.lifecycle_state !== expectedState || current.version !== expectedVersion) return false; this.institutionReleases.set(key, { ...current, lifecycle_state: nextState, version: current.version + 1, correlation_id: correlationId, trace_id: traceId }); return true; }
  private breakGlass = new Map<string, BreakGlassGrant>();
  async putBreakGlass(grant: BreakGlassGrant) { this.breakGlass.set(`${grant.tenant_id}:${grant.grant_id}`, structuredClone(grant)); }
  async getBreakGlass(tenantId: string, grantId: string) { return this.breakGlass.get(`${tenantId}:${grantId}`) ?? null; }
  async updateBreakGlass(grant: BreakGlassGrant) { const key = `${grant.tenant_id}:${grant.grant_id}`; if (!this.breakGlass.has(key)) return false; this.breakGlass.set(key, structuredClone(grant)); return true; }
  async getIdempotency(tenantId: string, key: string) { return this.idempotency.get(`${tenantId}:${key}`); }
  async claimIdempotency(tenantId: string, key: string, response: unknown) { const id = `${tenantId}:${key}`; if (this.idempotency.has(id)) return { claimed: false, response: this.idempotency.get(id) }; this.idempotency.set(id, structuredClone(response)); return { claimed: true, response }; }
  async putIdempotencyResponse(tenantId: string, key: string, response: unknown) { this.idempotency.set(`${tenantId}:${key}`, structuredClone(response)); }
  private outbox = new Map<string, OutboxMessage>();
  async enqueueOutbox(message: OutboxMessage) { const key = `${message.tenant_id}:${message.dedupe_key}`; if ([...this.outbox.values()].some(item => `${item.tenant_id}:${item.dedupe_key}` === key)) return false; this.outbox.set(`${message.tenant_id}:${message.outbox_id}`, { ...structuredClone(message), status: 'PENDING', attempts: 0 }); return true; }
  async claimOutbox(tenantId: string, workerId: string, leaseMs = 30000) { const now = Date.now(); const item = [...this.outbox.values()].find(candidate => candidate.tenant_id === tenantId && (candidate.status === 'PENDING' || (candidate.status === 'PROCESSING' && candidate.lease_expires_at && Date.parse(candidate.lease_expires_at) <= now)) && (!candidate.available_at || Date.parse(candidate.available_at) <= now)); if (!item) return null; item.status = 'PROCESSING'; item.worker_id = workerId; item.lease_expires_at = new Date(now + leaseMs).toISOString(); item.attempts = (item.attempts ?? 0) + 1; return structuredClone(item); }
  async completeOutbox(tenantId: string, outboxId: string) { const item = this.outbox.get(`${tenantId}:${outboxId}`); if (item) item.status = 'COMPLETED'; }
  async retryOutbox(tenantId: string, outboxId: string, error: string, maxAttempts = 5, delayMs?: number) { const item = this.outbox.get(`${tenantId}:${outboxId}`); if (!item) return 'DEAD_LETTER' as const; item.last_error = error; item.lease_expires_at = undefined; if ((item.attempts ?? 0) >= maxAttempts) { item.status = 'DEAD_LETTER'; return 'DEAD_LETTER' as const; } item.status = 'PENDING'; item.available_at = new Date(Date.now() + (delayMs ?? 250 * 2 ** Math.max(0, (item.attempts ?? 1) - 1))).toISOString(); return 'RETRYING' as const; }
  async getOutboxMetrics(tenantId: string) { const items = [...this.outbox.values()].filter(item => item.tenant_id === tenantId); const pending = items.filter(item => item.status === 'PENDING').length; const processing = items.filter(item => item.status === 'PROCESSING').length; const completed = items.filter(item => item.status === 'COMPLETED').length; const dead_letter = items.filter(item => item.status === 'DEAD_LETTER').length; const oldest = items.filter(item => item.status === 'PENDING').map(item => Date.parse(item.available_at ?? new Date().toISOString())).sort((a, b) => a - b)[0]; return { pending, processing, completed, dead_letter, oldest_age_ms: oldest ? Math.max(0, Date.now() - oldest) : null, retries: items.reduce((sum, item) => sum + Math.max(0, (item.attempts ?? 0) - 1), 0) }; }
  async requeueOutbox(tenantId: string, outboxId: string) { const item = this.outbox.get(`${tenantId}:${outboxId}`); if (!item || item.status !== 'DEAD_LETTER') return false; item.status = 'PENDING'; item.available_at = new Date().toISOString(); item.lease_expires_at = undefined; return true; }
  async getActorMembership(_tenantId: string, _actorId: string, _role: string) { return { active: true, facility_scope: '*', mandate_expires_at: '2099-01-01T00:00:00Z', financial_limit: 10000 }; }
}

/** Adapter contract for pg.Pool; production wiring supplies the query/transaction implementation. */
export interface SqlExecutor {
  query<T = unknown>(text: string, values?: unknown[]): Promise<{ rows: T[]; rowCount?: number }>;
  transaction?<T>(tenantId: string, work: (db: SqlExecutor) => Promise<T>): Promise<T>;
}
export class PostgreSQLPlatformRepositories implements PlatformRepositories {
  constructor(private readonly db: SqlExecutor) {}
  async transaction<T>(tenantId: string, work: (repositories: PlatformRepositories) => Promise<T>): Promise<T> {
    if (!this.db.transaction) return work(this);
    return this.db.transaction(tenantId, async scopedDb => work(new PostgreSQLPlatformRepositories(scopedDb)));
  }
  async lockScope(scopeId: string) { await this.db.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 0))', [scopeId]); }
  async appendEvent(event: EventEnvelope) { const result = await this.db.query('INSERT INTO journal_events (tenant_id,event_id,event_type,payload,recorded_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (tenant_id,event_id) DO NOTHING RETURNING event_id', [event.tenant_id, event.event_id, event.event_type, JSON.stringify(event), event.recorded_at]); return result.rows.length === 1; }
  async getEvents(tenantId: string, incidentId?: string) { const result = await this.db.query<EventEnvelope>('SELECT payload FROM journal_events WHERE tenant_id=$1 AND ($2::text IS NULL OR payload->>\'incident_id\'=$2) ORDER BY recorded_at,event_id', [tenantId, incidentId ?? null]); return result.rows.map(row => (row as unknown as { payload: EventEnvelope }).payload); }
  async putEvidence(record: EvidenceRecord & { tenant_id: string }) { await this.db.query('INSERT INTO evidence_records (tenant_id,evidence_id,payload) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,evidence_id) DO NOTHING', [record.tenant_id, record.evidence_id, JSON.stringify(record)]); }
  async getState(tenantId: string, scopeId: string) { const result = await this.db.query<{ version: number; values: Record<string, unknown> }>('SELECT version,values FROM state_snapshots WHERE tenant_id=$1 AND scope_id=$2', [tenantId, scopeId]); return result.rows[0] ?? null; }
  async putState(incident: StoredIncident, expectedVersion: number) {
    if (incident.state_version !== expectedVersion + 1) return false;
    const updated = await this.db.query('UPDATE state_snapshots SET version=$3::bigint, values=$5::jsonb, state_hash=$6 WHERE tenant_id=$1 AND scope_id=$2 AND version=$4::bigint RETURNING scope_id', [incident.tenant_id, incident.scope_id, incident.state_version, expectedVersion, JSON.stringify(incident.values ?? {}), incident.state_hash ?? '']);
    if (updated.rows.length === 1) return true;
    const inserted = await this.db.query('INSERT INTO state_snapshots (tenant_id,scope_id,version,values,state_hash) VALUES ($1,$2,$3::bigint,$4::jsonb,$5) ON CONFLICT (tenant_id,scope_id) DO NOTHING RETURNING scope_id', [incident.tenant_id, incident.scope_id, incident.state_version, JSON.stringify(incident.values ?? {}), incident.state_hash ?? '']);
    return inserted.rows.length === 1;
  }
  async putStateDiff(diff: StateDiff) { await this.db.query('INSERT INTO state_diffs (tenant_id,scope_id,version,diff,state_hash) VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING', [diff.tenant_id, diff.scope_id, diff.version, JSON.stringify(diff.diff), diff.state_hash]); }
  async linkEvidence(relationship: EvidenceRelationship) { await this.db.query('INSERT INTO evidence_relationships (tenant_id,relationship_id,event_id,evidence_id,relationship_type) VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING', [relationship.tenant_id, relationship.relationship_id, relationship.event_id, relationship.evidence_id, relationship.relationship_type]); }
  async putIncident(incident: StoredIncident) { await this.db.query('INSERT INTO incidents (tenant_id,incident_id,scope_id,state_version,status) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (tenant_id,incident_id) DO UPDATE SET state_version=EXCLUDED.state_version,status=EXCLUDED.status', [incident.tenant_id, incident.incident_id, incident.scope_id, incident.state_version, incident.status]); }
  async putProposal(proposal: ActionProposal & { tenant_id: string }) { await this.db.query('INSERT INTO proposals (tenant_id,proposal_id,payload) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,proposal_id) DO NOTHING', [proposal.tenant_id, proposal.proposal_id, JSON.stringify(proposal)]); }
  async getProposal(tenantId: string, proposalId: string) { const result = await this.db.query<{ payload: ActionProposal & { tenant_id: string } }>('SELECT payload FROM proposals WHERE tenant_id=$1 AND proposal_id=$2', [tenantId, proposalId]); return result.rows[0]?.payload ?? null; }
  async putReview(review: StoredReview & { tenant_id: string }) { await this.db.query('INSERT INTO human_reviews (tenant_id,review_id,payload) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,review_id) DO NOTHING', [review.tenant_id, review.review_id, JSON.stringify(review)]); }
  async getReview(tenantId: string, proposalId: string) { const result = await this.db.query<{ payload: StoredReview & { tenant_id: string } }>('SELECT payload FROM human_reviews WHERE tenant_id=$1 AND payload->>\'proposal_id\'=$2 ORDER BY recorded_at DESC LIMIT 1', [tenantId, proposalId]); return result.rows[0]?.payload ?? null; }
  async putKernelDecision(decision: StoredKernelDecision) { await this.db.query('INSERT INTO kernel_decisions (tenant_id,decision_id,proposal_id,payload,recorded_at) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (tenant_id,decision_id) DO NOTHING', [decision.tenant_id, decision.decision_id, decision.proposal_id, JSON.stringify(decision), decision.recorded_at ?? decision.evaluated_at]); }
  async getKernelDecision(tenantId: string, proposalId: string) { const result = await this.db.query<{ payload: StoredKernelDecision }>('SELECT payload FROM kernel_decisions WHERE tenant_id=$1 AND proposal_id=$2 ORDER BY recorded_at DESC, decision_id DESC LIMIT 1', [tenantId, proposalId]); return result.rows[0]?.payload ?? null; }
  async putMandate(mandate: Record<string, unknown> & { tenant_id: string }) { await this.db.query('INSERT INTO mandates (tenant_id,mandate_id,payload) VALUES ($1,$2,$3)', [mandate.tenant_id, String(mandate.mandate_id), JSON.stringify(mandate)]); }
  async putShadow(shadow: StoredShadow & { tenant_id: string }) { await this.db.query('INSERT INTO shadow_evaluations (tenant_id,proposal_id,payload) VALUES ($1,$2,$3)', [shadow.tenant_id, shadow.proposal_id, JSON.stringify(shadow)]); }
  async putOutcome(outcome: OutcomeRecord & { tenant_id: string }) { await this.db.query('INSERT INTO outcomes (tenant_id,outcome_id,payload) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,outcome_id) DO NOTHING', [outcome.tenant_id, outcome.outcome_id, JSON.stringify(outcome)]); }
  async getOutcome(tenantId: string, outcomeId: string) { const result = await this.db.query<{ payload: OutcomeRecord & { tenant_id: string } }>('SELECT payload FROM outcomes WHERE tenant_id=$1 AND outcome_id=$2', [tenantId, outcomeId]); return result.rows[0]?.payload ?? null; }
  async putReceipt(receipt: DecisionReceipt & { tenant_id: string }) { await this.db.query('INSERT INTO receipts (tenant_id,receipt_id,payload) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,receipt_id) DO NOTHING', [receipt.tenant_id, receipt.receipt_id, JSON.stringify(receipt)]); }
  async getReceipt(tenantId: string, receiptId: string) { const result = await this.db.query<{ payload: DecisionReceipt & { tenant_id: string }; custody: ReceiptCustodyRecord | null }>('SELECT r.payload, c.payload AS custody FROM receipts r LEFT JOIN receipt_custody c ON c.tenant_id=r.tenant_id AND c.receipt_id=r.receipt_id WHERE r.tenant_id=$1 AND r.receipt_id=$2', [tenantId, receiptId]); const row = result.rows[0]; if (!row) return null; return row.custody ? { ...row.payload, signature_status: row.custody.status, signature: row.custody.signature, digest: row.custody.digest, algorithm: row.custody.algorithm, key_id: row.custody.key_id, key_version: row.custody.key_version, signed_at: row.custody.signed_at } : row.payload; }
  async listReceipts(tenantId: string, incidentId?: string) { const result = await this.db.query<{ payload: DecisionReceipt & { tenant_id: string } }>('SELECT payload FROM receipts WHERE tenant_id=$1 AND ($2::text IS NULL OR payload->>\'incident_id\'=$2) ORDER BY receipt_id', [tenantId, incidentId ?? null]); return result.rows.map(row => row.payload); }
  async putReceiptCustody(record: ReceiptCustodyRecord) { const result = await this.db.query('INSERT INTO receipt_custody (tenant_id,receipt_id,payload) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,receipt_id) DO NOTHING RETURNING receipt_id', [record.tenant_id, record.receipt_id, JSON.stringify(record)]); return result.rows.length === 1; }
  async getReceiptCustody(tenantId: string, receiptId: string) { const result = await this.db.query<{ payload: ReceiptCustodyRecord }>('SELECT payload FROM receipt_custody WHERE tenant_id=$1 AND receipt_id=$2', [tenantId, receiptId]); return result.rows[0]?.payload ?? null; }
  async claimReceiptSigning(tenantId: string, receiptId: string, workerId: string, leaseMs = 30000) { const result = await this.db.query('INSERT INTO receipt_signing_claims (tenant_id,receipt_id,worker_id,lease_expires_at) VALUES ($1,$2,$3,now()+($4::integer * interval \'1 millisecond\')) ON CONFLICT (tenant_id,receipt_id) DO UPDATE SET worker_id=EXCLUDED.worker_id,lease_expires_at=EXCLUDED.lease_expires_at WHERE receipt_signing_claims.status=\'CLAIMED\' AND receipt_signing_claims.lease_expires_at<=now() RETURNING receipt_id', [tenantId, receiptId, workerId, leaseMs]); return result.rows.length === 1; }
  async completeReceiptSigning(tenantId: string, receiptId: string) { await this.db.query("UPDATE receipt_signing_claims SET status='COMPLETED', lease_expires_at=now() WHERE tenant_id=$1 AND receipt_id=$2 AND status='CLAIMED'", [tenantId, receiptId]); }
  async putBreakGlass(grant: BreakGlassGrant) { await this.db.query('INSERT INTO break_glass_grants (tenant_id,grant_id,incident_id,payload,status,expires_at) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (tenant_id,grant_id) DO NOTHING', [grant.tenant_id, grant.grant_id, grant.incident_id, JSON.stringify(grant), grant.status, grant.expires_at ?? null]); }
  async getBreakGlass(tenantId: string, grantId: string) { const result = await this.db.query<{ payload: BreakGlassGrant }>('SELECT payload FROM break_glass_grants WHERE tenant_id=$1 AND grant_id=$2', [tenantId, grantId]); return result.rows[0]?.payload ?? null; }
  async updateBreakGlass(grant: BreakGlassGrant) { const result = await this.db.query('UPDATE break_glass_grants SET payload=$3,status=$4,expires_at=$5 WHERE tenant_id=$1 AND grant_id=$2', [grant.tenant_id, grant.grant_id, JSON.stringify(grant), grant.status, grant.expires_at ?? null]); return result.rowCount === 1; }
  async getIdempotency(tenantId: string, key: string) { const result = await this.db.query<{ response: unknown }>('SELECT response FROM idempotency_keys WHERE tenant_id=$1 AND key=$2', [tenantId, key]); return result.rows[0]?.response; }
  async claimIdempotency(tenantId: string, key: string, response: unknown) { const result = await this.db.query<{ response: unknown }>('INSERT INTO idempotency_keys (tenant_id,key,response) VALUES ($1,$2,$3) ON CONFLICT (tenant_id,key) DO NOTHING RETURNING response', [tenantId, key, JSON.stringify(response)]); if (result.rows.length) return { claimed: true, response }; const existing = await this.db.query<{ response: unknown }>('SELECT response FROM idempotency_keys WHERE tenant_id=$1 AND key=$2', [tenantId, key]); return { claimed: false, response: existing.rows[0]?.response }; }
  async putIdempotencyResponse(tenantId: string, key: string, response: unknown) { await this.db.query('UPDATE idempotency_keys SET response=$3::jsonb WHERE tenant_id=$1 AND key=$2', [tenantId, key, JSON.stringify(response)]); }
  async enqueueOutbox(message: OutboxMessage) { const result = await this.db.query('INSERT INTO transactional_outbox (tenant_id,outbox_id,dedupe_key,topic,aggregate_id,payload,correlation_id,trace_id,state_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (tenant_id,dedupe_key) DO NOTHING RETURNING outbox_id', [message.tenant_id, message.outbox_id, message.dedupe_key, message.topic, message.aggregate_id, JSON.stringify(message.payload), message.correlation_id, message.trace_id, message.state_version ?? null]); return result.rows.length === 1; }
  async claimOutbox(tenantId: string, workerId: string, leaseMs = 30000) { const result = await this.db.query<OutboxMessage & { payload: Record<string, unknown> }>(`UPDATE transactional_outbox SET status='PROCESSING', attempts=attempts+1, locked_at=now(), lease_expires_at=now() + ($3::integer * interval '1 millisecond'), worker_id=$2 WHERE tenant_id=$1 AND outbox_id=(SELECT outbox_id FROM transactional_outbox WHERE tenant_id=$1 AND available_at<=now() AND (status='PENDING' OR (status='PROCESSING' AND lease_expires_at<=now())) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`, [tenantId, workerId, leaseMs]); if (!result.rows[0]) return null; return { ...result.rows[0], status: 'PROCESSING' as const, attempts: result.rows[0].attempts, payload: result.rows[0].payload }; }
  async completeOutbox(tenantId: string, outboxId: string) { await this.db.query("UPDATE transactional_outbox SET status='COMPLETED', completed_at=now(), lease_expires_at=NULL WHERE tenant_id=$1 AND outbox_id=$2 AND status='PROCESSING'", [tenantId, outboxId]); }
  async retryOutbox(tenantId: string, outboxId: string, error: string, maxAttempts = 5, delayMs?: number) { const result = await this.db.query<{ attempts: number }>('SELECT attempts FROM transactional_outbox WHERE tenant_id=$1 AND outbox_id=$2', [tenantId, outboxId]); const attempts = Number(result.rows[0]?.attempts ?? maxAttempts); const dead = attempts >= maxAttempts; await this.db.query(`UPDATE transactional_outbox SET status=$3, available_at=now() + ($4::integer * interval '1 millisecond'), lease_expires_at=NULL, last_error=$5, last_error_code=$6, last_error_metadata=$7::jsonb WHERE tenant_id=$1 AND outbox_id=$2`, [tenantId, outboxId, dead ? 'DEAD_LETTER' : 'PENDING', dead ? 0 : (delayMs ?? 250 * 2 ** Math.max(0, attempts - 1)), error.slice(0, 1000), dead ? 'WORKER_EXHAUSTED' : 'WORKER_RETRY', JSON.stringify({ attempts, max_attempts: maxAttempts })]); return dead ? 'DEAD_LETTER' as const : 'RETRYING' as const; }
  async getOutboxMetrics(tenantId: string) { const result = await this.db.query<{ pending: string; processing: string; completed: string; dead_letter: string; oldest_age_ms: string | null; retries: string }>(`SELECT count(*) FILTER (WHERE status='PENDING') pending, count(*) FILTER (WHERE status='PROCESSING') processing, count(*) FILTER (WHERE status='COMPLETED') completed, count(*) FILTER (WHERE status='DEAD_LETTER') dead_letter, EXTRACT(EPOCH FROM (now()-min(created_at) FILTER (WHERE status='PENDING')))*1000 oldest_age_ms, coalesce(sum(GREATEST(attempts-1,0)),0) retries FROM transactional_outbox WHERE tenant_id=$1`, [tenantId]); const row = result.rows[0]; return { pending: Number(row?.pending ?? 0), processing: Number(row?.processing ?? 0), completed: Number(row?.completed ?? 0), dead_letter: Number(row?.dead_letter ?? 0), oldest_age_ms: row?.oldest_age_ms == null ? null : Number(row.oldest_age_ms), retries: Number(row?.retries ?? 0) }; }
  async requeueOutbox(tenantId: string, outboxId: string) { const result = await this.db.query("UPDATE transactional_outbox SET status='PENDING', available_at=now(), lease_expires_at=NULL, last_error_code='GOVERNED_REQUEUE' WHERE tenant_id=$1 AND outbox_id=$2 AND status='DEAD_LETTER' RETURNING outbox_id", [tenantId, outboxId]); return result.rows.length === 1; }
  async putExecution(command: ExecutionCommand) { const result = await this.db.query('INSERT INTO execution_commands (tenant_id,command_id,incident_id,proposal_id,status,command_hash,authorization_id,proposal_hash,state_version,external_idempotency_key,payload) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (tenant_id,command_id) DO NOTHING RETURNING command_id', [command.tenant_id, command.command_id, command.incident_id, command.proposal_id, command.status, command.command_hash, command.authorization_id, command.proposal_hash, command.state_version, command.external_idempotency_key, JSON.stringify(command)]); return result.rows.length === 1; }
  async getExecution(tenantId: string, commandId: string) { const result = await this.db.query<{ payload: ExecutionCommand & { tenant_id: string } }>('SELECT payload FROM execution_commands WHERE tenant_id=$1 AND command_id=$2', [tenantId, commandId]); return result.rows[0]?.payload ?? null; }
  async updateExecution(command: ExecutionCommand & { tenant_id: string }, expectedStatus: ExecutionStatus) { const result = await this.db.query('UPDATE execution_commands SET status=$3,payload=$4,updated_at=now() WHERE tenant_id=$1 AND command_id=$2 AND status=$5 RETURNING command_id', [command.tenant_id, command.command_id, command.status, JSON.stringify(command), expectedStatus]); return result.rows.length === 1; }
  async putExecutionTransition(transition: ExecutionTransition) { const result = await this.db.query('INSERT INTO execution_transitions (tenant_id,transition_id,command_id,from_status,to_status,payload,recorded_at) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (tenant_id,transition_id) DO NOTHING RETURNING transition_id', [transition.tenant_id, transition.transition_id, transition.command_id, transition.from_status, transition.to_status, JSON.stringify(transition.payload), transition.recorded_at]); return result.rows.length === 1; }
  async listExecutionTransitions(tenantId: string, commandId: string) { const result = await this.db.query<ExecutionTransition>('SELECT tenant_id,transition_id,command_id,from_status,to_status,payload,recorded_at FROM execution_transitions WHERE tenant_id=$1 AND command_id=$2 ORDER BY recorded_at,transition_id', [tenantId, commandId]); return result.rows; }
  async listExecutions(tenantId: string, incidentId?: string) { const result = await this.db.query<{ payload: ExecutionCommand & { tenant_id: string } }>('SELECT payload FROM execution_commands WHERE tenant_id=$1 AND ($2::text IS NULL OR incident_id=$2) ORDER BY created_at,command_id', [tenantId, incidentId ?? null]); return result.rows.map(row => row.payload); }
  async putInstitutionSource(source: InstitutionSourceRecord) { const result = await this.db.query('INSERT INTO institution_sources (tenant_id,institution_id,source_id,source_version,owner_id,provenance,sensitivity,effective_from,effective_to,content_hash,classification_status,ingestion_timestamp,payload) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT DO NOTHING RETURNING source_id', [source.tenant_id, source.institution_id, source.source_id, source.source_version, source.owner_id, source.provenance, source.sensitivity, source.effective_from, source.effective_to ?? null, source.content_hash, source.classification_status, source.ingestion_timestamp, JSON.stringify(source.payload)]); return result.rows.length === 1; }
  async listInstitutionSources(tenantId: string, institutionId: string) { const result = await this.db.query<InstitutionSourceRecord>('SELECT tenant_id,institution_id,source_id,source_version,owner_id,provenance,sensitivity,effective_from,effective_to,content_hash,classification_status,ingestion_timestamp,payload FROM institution_sources WHERE tenant_id=$1 AND institution_id=$2 ORDER BY source_id,source_version', [tenantId, institutionId]); return result.rows; }
  async listInstitutionSourceVersions(tenantId: string, institutionId: string, sourceId: string) { const result = await this.db.query<InstitutionSourceRecord>('SELECT tenant_id,institution_id,source_id,source_version,owner_id,provenance,sensitivity,effective_from,effective_to,content_hash,classification_status,ingestion_timestamp,payload FROM institution_sources WHERE tenant_id=$1 AND institution_id=$2 AND source_id=$3 ORDER BY source_version', [tenantId, institutionId, sourceId]); return result.rows; }
  async createInstitutionCandidate(candidate: InstitutionCandidateRecord) { const result = await this.db.query('INSERT INTO institution_ir_candidates (tenant_id,institution_id,candidate_id,version,ir_hash,compiler_version,input_source_hashes,validation_findings,previous_candidate_id,control_graph_diff,status,payload) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10::jsonb,$11,$12::jsonb) ON CONFLICT DO NOTHING RETURNING candidate_id', [candidate.tenant_id, candidate.institution_id, candidate.candidate_id, candidate.version, candidate.ir_hash, candidate.compiler_version, JSON.stringify(candidate.input_source_hashes), JSON.stringify(candidate.validation_findings), candidate.previous_candidate_id ?? null, JSON.stringify(candidate.control_graph_diff), candidate.status, JSON.stringify(candidate.payload)]); return result.rows.length === 1; }
  async getInstitutionCandidate(tenantId: string, institutionId: string, candidateId: string) { const result = await this.db.query<InstitutionCandidateRecord>('SELECT tenant_id,institution_id,candidate_id,version,ir_hash,compiler_version,input_source_hashes,validation_findings,previous_candidate_id,control_graph_diff,status,payload,created_at FROM institution_ir_candidates WHERE tenant_id=$1 AND institution_id=$2 AND candidate_id=$3', [tenantId, institutionId, candidateId]); const row = result.rows[0]; return row ? { ...row, input_source_hashes: Array.isArray(row.input_source_hashes) ? row.input_source_hashes : [], validation_findings: Array.isArray(row.validation_findings) ? row.validation_findings : [], control_graph_diff: row.control_graph_diff ?? {}, payload: row.payload ?? {} } : null; }
  async createInstitutionRelease(release: InstitutionReleaseRecord) { const result = await this.db.query('INSERT INTO institution_releases (tenant_id,institution_id,release_id,candidate_id,version,lifecycle_state,manifest_hash,signature_status,correlation_id,trace_id,payload) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT DO NOTHING RETURNING release_id', [release.tenant_id, release.institution_id, release.release_id, release.candidate_id, release.version, release.lifecycle_state, release.manifest_hash, release.signature_status, release.correlation_id ?? null, release.trace_id ?? null, JSON.stringify(release.payload)]); return result.rows.length === 1; }
  async getInstitutionRelease(tenantId: string, releaseId: string) { const result = await this.db.query<InstitutionReleaseRecord>('SELECT tenant_id,institution_id,release_id,candidate_id,version,lifecycle_state,manifest_hash,signature_status,correlation_id,trace_id,payload FROM institution_releases WHERE tenant_id=$1 AND release_id=$2', [tenantId, releaseId]); const row = result.rows[0]; return row ? { ...row, version: Number(row.version) } : null; }
  async transitionInstitutionRelease(tenantId: string, releaseId: string, expectedState: string, expectedVersion: number, nextState: string, correlationId: string, traceId: string, _payload: Record<string, unknown>) { const result = await this.db.query('UPDATE institution_releases SET lifecycle_state=$5,version=version+1,correlation_id=$6,trace_id=$7 WHERE tenant_id=$1 AND release_id=$2 AND lifecycle_state=$3 AND version=$4 RETURNING release_id', [tenantId, releaseId, expectedState, expectedVersion, nextState, correlationId, traceId]); return result.rows.length === 1; }
  async getActorMembership(tenantId: string, actorId: string, role: string) { const result = await this.db.query<{ active: boolean; facility_scope: string | null; mandate_expires_at: string | null; financial_limit: number | null }>('SELECT active,facility_scope,mandate_expires_at,financial_limit FROM actor_memberships WHERE tenant_id=$1 AND actor_id=$2 AND role=$3', [tenantId, actorId, role]); return result.rows[0] ?? null; }
}


